import { TRPCError } from "@trpc/server";
import { and, desc, eq, gt, isNull, lt, or } from "drizzle-orm";
import { z } from "zod";
import { administrativeActivityTimeline, executiveAssignments, executiveDecisions, executiveDelegations, executiveDocuments, executiveInboxItems, executiveMeetings, executiveRequests, executiveWeeklyReports, appRoles, companies, documents, tenantUsers, users } from "../../drizzle/schema";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";

const assistantRoles = ["executive_assistant", "super_admin", "general_manager"] as const;
const leadershipRoles = ["super_admin", "general_manager"] as const;
const priorities = ["low", "normal", "high", "urgent"] as const;
const decisionStatuses = ["issued", "assigned", "in_progress", "waiting", "completed", "closed"] as const;
const requestTypes = ["schedule_meeting", "follow_up_task", "request_report", "prepare_document", "reminder", "contact_manager", "prepare_minutes", "request_update"] as const;
const requestStatuses = ["new", "in_review", "assigned", "in_progress", "completed", "cancelled"] as const;
const delegationPermissions = ["can_schedule_on_behalf_of_ceo", "can_request_reports_on_behalf_of_ceo", "can_follow_up_on_behalf_of_ceo", "can_send_internal_reminder_on_behalf_of_ceo"] as const;
const scopeInput = z.object({ tenantId: z.number().int().positive(), companyId: z.number().int().positive() });

async function requireActor(userId: number, input: { tenantId: number; companyId: number }) {
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "SERVICE_UNAVAILABLE", message: "قاعدة البيانات غير متاحة حالياً." });
  const [actor] = await db.select({ membership: tenantUsers, role: appRoles, company: companies }).from(tenantUsers).leftJoin(appRoles, eq(tenantUsers.roleId, appRoles.id)).innerJoin(companies, eq(tenantUsers.companyId, companies.id)).where(and(eq(tenantUsers.userId, userId), eq(tenantUsers.tenantId, input.tenantId), eq(tenantUsers.companyId, input.companyId), eq(tenantUsers.status, "active"))).limit(1);
  if (!actor || !assistantRoles.includes((actor.role?.code ?? "read_only") as typeof assistantRoles[number])) throw new TRPCError({ code: "FORBIDDEN", message: "مساحة مساعد المدير التنفيذي متاحة للدور المخصص أو الإدارة المخولة فقط." });
  return { db, roleCode: actor.role?.code ?? "read_only" };
}

async function assertMember(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, input: { tenantId: number; companyId: number; userId: number }) {
  const [member] = await db.select({ id: tenantUsers.id }).from(tenantUsers).where(and(eq(tenantUsers.tenantId, input.tenantId), eq(tenantUsers.companyId, input.companyId), eq(tenantUsers.userId, input.userId), eq(tenantUsers.status, "active"))).limit(1);
  if (!member) throw new TRPCError({ code: "BAD_REQUEST", message: "المستخدم المحدد ليس عضواً نشطاً في الشركة." });
}

async function log(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, input: { tenantId: number; companyId: number; actorUserId: number; entityType: string; entityId: number; action: string; description: string; }) {
  await db.insert(administrativeActivityTimeline).values(input);
}

export const executiveAssistantRouter = router({
  dashboard: protectedProcedure.input(scopeInput).query(async ({ ctx, input }) => {
    const { db, roleCode } = await requireActor(ctx.user.id, input);
    const personal = roleCode === "executive_assistant";
    const today = new Date();
    const [decisions, requests, meetings, assignments, inbox, reports, delegations] = await Promise.all([
      db.select({ decision: executiveDecisions, responsible: users }).from(executiveDecisions).leftJoin(users, eq(executiveDecisions.responsibleUserId, users.id)).where(and(eq(executiveDecisions.tenantId, input.tenantId), eq(executiveDecisions.companyId, input.companyId), personal ? or(eq(executiveDecisions.createdByUserId, ctx.user.id), eq(executiveDecisions.responsibleUserId, ctx.user.id)) : undefined)).orderBy(desc(executiveDecisions.dueDate), desc(executiveDecisions.updatedAt)).limit(40),
      db.select().from(executiveRequests).where(and(eq(executiveRequests.tenantId, input.tenantId), eq(executiveRequests.companyId, input.companyId), personal ? eq(executiveRequests.requestedByUserId, ctx.user.id) : undefined)).orderBy(desc(executiveRequests.createdAt)).limit(40),
      db.select().from(executiveMeetings).where(and(eq(executiveMeetings.tenantId, input.tenantId), eq(executiveMeetings.companyId, input.companyId), gt(executiveMeetings.startAt, today))).orderBy(executiveMeetings.startAt).limit(20),
      db.select({ assignment: executiveAssignments, assignee: users }).from(executiveAssignments).innerJoin(users, eq(executiveAssignments.assignedToUserId, users.id)).where(and(eq(executiveAssignments.tenantId, input.tenantId), eq(executiveAssignments.companyId, input.companyId), personal ? or(eq(executiveAssignments.createdByUserId, ctx.user.id), eq(executiveAssignments.assignedToUserId, ctx.user.id)) : undefined)).orderBy(desc(executiveAssignments.dueDate)).limit(40),
      db.select().from(executiveInboxItems).where(and(eq(executiveInboxItems.tenantId, input.tenantId), eq(executiveInboxItems.companyId, input.companyId), eq(executiveInboxItems.status, "open"))).orderBy(desc(executiveInboxItems.priority), executiveInboxItems.dueAt).limit(30),
      db.select().from(executiveWeeklyReports).where(and(eq(executiveWeeklyReports.tenantId, input.tenantId), eq(executiveWeeklyReports.companyId, input.companyId), personal ? eq(executiveWeeklyReports.submittedByUserId, ctx.user.id) : undefined)).orderBy(desc(executiveWeeklyReports.weekStart)).limit(10),
      db.select().from(executiveDelegations).where(and(eq(executiveDelegations.tenantId, input.tenantId), eq(executiveDelegations.companyId, input.companyId), eq(executiveDelegations.assistantUserId, ctx.user.id), gt(executiveDelegations.endsAt, today), isNull(executiveDelegations.revokedAt))).orderBy(desc(executiveDelegations.endsAt)),
    ]);
    const needsToday = [
      ...decisions.filter(({ decision }) => !["completed", "closed"].includes(decision.status) && (!decision.dueDate || decision.dueDate.getTime() <= Date.now() + 86400000)).map(({ decision }) => ({ type: "قرار", title: decision.title, id: decision.id })),
      ...assignments.filter(({ assignment }) => !["completed", "cancelled"].includes(assignment.status) && assignment.dueDate.getTime() <= Date.now() + 86400000).map(({ assignment }) => ({ type: "مهمة", title: assignment.title, id: assignment.id })),
      ...inbox.filter((item) => item.priority === "urgent" || (item.dueAt && item.dueAt.getTime() <= Date.now() + 3600000)).map((item) => ({ type: "صندوق المدير", title: item.title, id: item.id })),
    ].slice(0, 12);
    return { roleCode, decisions, requests, meetings, assignments, inbox, reports, delegations, needsToday, metrics: { openDecisions: decisions.filter(({ decision }) => !["completed", "closed"].includes(decision.status)).length, upcomingMeetings: meetings.length, openRequests: requests.filter((item) => !["completed", "cancelled"].includes(item.status)).length, pendingInbox: inbox.length, overdueAssignments: assignments.filter(({ assignment }) => assignment.dueDate.getTime() < Date.now() && !["completed", "cancelled"].includes(assignment.status)).length } };
  }),

  createDecision: protectedProcedure.input(scopeInput.extend({ title: z.string().trim().min(2).max(255), decisionDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), responsibleDepartment: z.string().trim().max(128).optional(), responsibleUserId: z.number().int().positive().optional(), requirement: z.string().trim().min(2).max(10000), dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), priority: z.number().int().min(0).max(100).default(0) })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); if (input.responsibleUserId) await assertMember(db, { ...input, userId: input.responsibleUserId }); const result = await db.insert(executiveDecisions).values({ tenantId: input.tenantId, companyId: input.companyId, title: input.title, decisionDate: new Date(`${input.decisionDate}T00:00:00.000Z`), responsibleDepartment: input.responsibleDepartment || null, responsibleUserId: input.responsibleUserId || null, requirement: input.requirement, dueDate: input.dueDate ? new Date(`${input.dueDate}T00:00:00.000Z`) : null, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "executive_decision", entityId: id, action: "created", description: "تم إنشاء قرار تنفيذي للمتابعة." }); return { id }; }),
  updateDecision: protectedProcedure.input(scopeInput.extend({ decisionId: z.number().int().positive(), status: z.enum(decisionStatuses).optional(), completionPercent: z.number().int().min(0).max(100).optional(), latestUpdate: z.string().trim().max(5000).optional(), dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const [decision] = await db.select().from(executiveDecisions).where(and(eq(executiveDecisions.id, input.decisionId), eq(executiveDecisions.tenantId, input.tenantId), eq(executiveDecisions.companyId, input.companyId))).limit(1); if (!decision) throw new TRPCError({ code: "NOT_FOUND", message: "القرار التنفيذي غير موجود." }); await db.update(executiveDecisions).set({ status: input.status ?? decision.status, completionPercent: input.completionPercent ?? decision.completionPercent, latestUpdate: input.latestUpdate ?? decision.latestUpdate, dueDate: input.dueDate ? new Date(`${input.dueDate}T00:00:00.000Z`) : decision.dueDate }).where(eq(executiveDecisions.id, decision.id)); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "executive_decision", entityId: decision.id, action: "updated", description: "تم تحديث متابعة القرار التنفيذي دون تغيير نص القرار الأصلي." }); return { updated: true } as const; }),
  createRequest: protectedProcedure.input(scopeInput.extend({ requestType: z.enum(requestTypes), title: z.string().trim().min(2).max(255), description: z.string().trim().min(2).max(10000), priority: z.enum(priorities).default("normal"), dueDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const result = await db.insert(executiveRequests).values({ tenantId: input.tenantId, companyId: input.companyId, requestType: input.requestType, title: input.title, description: input.description, priority: input.priority, requestedByUserId: ctx.user.id, dueDate: input.dueDate ? new Date(`${input.dueDate}T00:00:00.000Z`) : null }); const id = Number(result[0].insertId); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "executive_request", entityId: id, action: "created", description: "تم إنشاء طلب تنفيذي." }); return { id }; }),
  updateRequest: protectedProcedure.input(scopeInput.extend({ requestId: z.number().int().positive(), status: z.enum(requestStatuses), note: z.string().trim().max(5000).optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const [request] = await db.select().from(executiveRequests).where(and(eq(executiveRequests.id, input.requestId), eq(executiveRequests.tenantId, input.tenantId), eq(executiveRequests.companyId, input.companyId))).limit(1); if (!request) throw new TRPCError({ code: "NOT_FOUND", message: "الطلب التنفيذي غير موجود." }); await db.update(executiveRequests).set({ status: input.status, completedAt: input.status === "completed" ? new Date() : null }).where(eq(executiveRequests.id, request.id)); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "executive_request", entityId: request.id, action: "updated", description: input.note || "تم تحديث حالة الطلب التنفيذي." }); return { updated: true } as const; }),
  createMeeting: protectedProcedure.input(scopeInput.extend({ title: z.string().trim().min(2).max(255), startAt: z.string().datetime(), endAt: z.string().datetime().optional(), meetingLink: z.string().url().max(500).optional(), participants: z.string().max(5000).optional(), agenda: z.string().max(10000).optional(), brief: z.string().max(10000).optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const result = await db.insert(executiveMeetings).values({ tenantId: input.tenantId, companyId: input.companyId, title: input.title, startAt: new Date(input.startAt), endAt: input.endAt ? new Date(input.endAt) : null, meetingLink: input.meetingLink || null, participants: input.participants || null, agenda: input.agenda || null, brief: input.brief || null, createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "executive_meeting", entityId: id, action: "created", description: "تم إنشاء اجتماع تنفيذي." }); return { id }; }),
  updateMeeting: protectedProcedure.input(scopeInput.extend({ meetingId: z.number().int().positive(), brief: z.string().max(10000).optional(), minutes: z.string().max(20000).optional(), actionItems: z.string().max(20000).optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const [meeting] = await db.select().from(executiveMeetings).where(and(eq(executiveMeetings.id, input.meetingId), eq(executiveMeetings.tenantId, input.tenantId), eq(executiveMeetings.companyId, input.companyId))).limit(1); if (!meeting) throw new TRPCError({ code: "NOT_FOUND", message: "الاجتماع التنفيذي غير موجود." }); await db.update(executiveMeetings).set({ brief: input.brief ?? meeting.brief, minutes: input.minutes ?? meeting.minutes, actionItems: input.actionItems ?? meeting.actionItems }).where(eq(executiveMeetings.id, meeting.id)); return { updated: true } as const; }),
  grantDelegation: protectedProcedure.input(scopeInput.extend({ assistantUserId: z.number().int().positive(), permission: z.enum(delegationPermissions), startsAt: z.string().datetime(), endsAt: z.string().datetime() })).mutation(async ({ ctx, input }) => { const { db, roleCode } = await requireActor(ctx.user.id, input); if (!leadershipRoles.includes(roleCode as typeof leadershipRoles[number])) throw new TRPCError({ code: "FORBIDDEN", message: "التفويض التنفيذي لا يمنح إلا من الرئيس التنفيذي أو الإدارة المخولة." }); if (new Date(input.endsAt) <= new Date(input.startsAt)) throw new TRPCError({ code: "BAD_REQUEST", message: "نهاية التفويض يجب أن تكون بعد بدايته." }); await assertMember(db, { ...input, userId: input.assistantUserId }); const [assistantRole] = await db.select({ role: appRoles }).from(tenantUsers).leftJoin(appRoles, eq(tenantUsers.roleId, appRoles.id)).where(and(eq(tenantUsers.tenantId, input.tenantId), eq(tenantUsers.companyId, input.companyId), eq(tenantUsers.userId, input.assistantUserId), eq(tenantUsers.status, "active"))).limit(1); if (assistantRole?.role?.code !== "executive_assistant") throw new TRPCError({ code: "BAD_REQUEST", message: "التفويض مخصص لمساعد المدير التنفيذي فقط." }); const result = await db.insert(executiveDelegations).values({ tenantId: input.tenantId, companyId: input.companyId, assistantUserId: input.assistantUserId, permission: input.permission, startsAt: new Date(input.startsAt), endsAt: new Date(input.endsAt), grantedByUserId: ctx.user.id }); const id = Number(result[0].insertId); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "executive_delegation", entityId: id, action: "granted", description: `تم منح تفويض مؤقت: ${input.permission}.` }); return { id }; }),
  listDocuments: protectedProcedure.input(scopeInput).query(async ({ ctx, input }) => { const { db, roleCode } = await requireActor(ctx.user.id, input); const allowed = roleCode === "executive_assistant" ? or(eq(executiveDocuments.accessScope, "general"), eq(executiveDocuments.accessScope, "executive"), eq(executiveDocuments.sharedWithUserId, ctx.user.id)) : undefined; return db.select({ executiveDocument: executiveDocuments, document: documents }).from(executiveDocuments).innerJoin(documents, eq(executiveDocuments.documentId, documents.id)).where(and(eq(executiveDocuments.tenantId, input.tenantId), eq(executiveDocuments.companyId, input.companyId), allowed)).orderBy(desc(executiveDocuments.createdAt)).limit(100); }),
  generateBrief: protectedProcedure.input(scopeInput.extend({ period: z.enum(["daily", "weekly"]).default("daily") })).query(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const report = await db.select().from(executiveWeeklyReports).where(and(eq(executiveWeeklyReports.tenantId, input.tenantId), eq(executiveWeeklyReports.companyId, input.companyId))).orderBy(desc(executiveWeeklyReports.weekStart)).limit(1); const decisions = await db.select().from(executiveDecisions).where(and(eq(executiveDecisions.tenantId, input.tenantId), eq(executiveDecisions.companyId, input.companyId), or(eq(executiveDecisions.status, "issued"), eq(executiveDecisions.status, "waiting"), eq(executiveDecisions.status, "in_progress")))).orderBy(desc(executiveDecisions.dueDate)).limit(10); const meetings = await db.select().from(executiveMeetings).where(and(eq(executiveMeetings.tenantId, input.tenantId), eq(executiveMeetings.companyId, input.companyId), gt(executiveMeetings.startAt, new Date()))).orderBy(executiveMeetings.startAt).limit(input.period === "daily" ? 5 : 20); return { period: input.period, generatedAt: new Date(), headline: input.period === "daily" ? "موجز المدير التنفيذي اليومي" : "الموجز التنفيذي الأسبوعي", meetings, decisions, latestReport: report[0] ?? null, guardrail: "هذا الموجز يلخص وينظم ويقترح فقط؛ لا يعتمد أو ينفذ قرارات حساسة تلقائياً." }; }),
});

export type ExecutiveAssistantRouter = typeof executiveAssistantRouter;
