import { TRPCError } from "@trpc/server";
import { and, desc, eq } from "drizzle-orm";
import { z } from "zod";
import { administrativeActivityTimeline, appRoles, branches, companies, operationalCorrectiveActions, operationalIssues, operationalKpis, operationalRequests, operationalSlaPolicies, operationalTasks, tenantUsers, users } from "../../drizzle/schema";
import { getDb } from "../db";
import { protectedProcedure, router } from "../_core/trpc";

const managerRoles = ["operations_manager", "super_admin", "general_manager"] as const;
const taskStatuses = ["new", "assigned", "in_progress", "waiting", "blocked", "escalated", "completed", "cancelled"] as const;
const priorities = ["low", "normal", "high", "critical"] as const;
const issueStatuses = ["new", "assigned", "investigation", "action_required", "resolved", "closed"] as const;
const severities = ["low", "medium", "high", "critical"] as const;
const scopeInput = z.object({ tenantId: z.number().int().positive(), companyId: z.number().int().positive() });
type ScopeInput = z.infer<typeof scopeInput>;

async function requireActor(userId: number, input: ScopeInput) {
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "SERVICE_UNAVAILABLE", message: "قاعدة البيانات غير متاحة حالياً." });
  const [actor] = await db.select({ roleCode: appRoles.code, companyId: companies.id }).from(tenantUsers).leftJoin(appRoles, eq(tenantUsers.roleId, appRoles.id)).innerJoin(companies, eq(tenantUsers.companyId, companies.id)).where(and(eq(tenantUsers.userId, userId), eq(tenantUsers.tenantId, input.tenantId), eq(tenantUsers.companyId, input.companyId), eq(tenantUsers.status, "active"))).limit(1);
  if (!actor || !managerRoles.includes((actor.roleCode ?? "") as (typeof managerRoles)[number])) throw new TRPCError({ code: "FORBIDDEN", message: "هذا المسار مخصص لمدير العمليات والصلاحيات الإدارية التشغيلية المخولة فقط." });
  return { db, roleCode: actor.roleCode ?? "operations_manager" };
}
function dateValue(value?: string | null) { return value ? new Date(value) : null; }
async function log(db: NonNullable<Awaited<ReturnType<typeof getDb>>>, input: ScopeInput & { actorUserId: number; entityType: string; entityId: number; action: string; description: string }) { await db.insert(administrativeActivityTimeline).values(input); }

export const operationsControlRouter = router({
  dashboard: protectedProcedure.input(scopeInput).query(async ({ ctx, input }) => {
    const { db, roleCode } = await requireActor(ctx.user.id, input);
    const [tasks, issues, requests, actions, members, branchRows, kpis, slaPolicies] = await Promise.all([
      db.select({ task: operationalTasks, assignee: users }).from(operationalTasks).leftJoin(users, eq(operationalTasks.assignedToUserId, users.id)).where(and(eq(operationalTasks.tenantId, input.tenantId), eq(operationalTasks.companyId, input.companyId))).orderBy(desc(operationalTasks.dueAt), desc(operationalTasks.updatedAt)).limit(200),
      db.select({ issue: operationalIssues, assignee: users }).from(operationalIssues).leftJoin(users, eq(operationalIssues.assignedToUserId, users.id)).where(and(eq(operationalIssues.tenantId, input.tenantId), eq(operationalIssues.companyId, input.companyId))).orderBy(desc(operationalIssues.resolutionDueAt), desc(operationalIssues.updatedAt)).limit(200),
      db.select({ request: operationalRequests, assignee: users }).from(operationalRequests).leftJoin(users, eq(operationalRequests.assignedToUserId, users.id)).where(and(eq(operationalRequests.tenantId, input.tenantId), eq(operationalRequests.companyId, input.companyId))).orderBy(desc(operationalRequests.dueAt), desc(operationalRequests.updatedAt)).limit(200),
      db.select({ action: operationalCorrectiveActions, assignee: users }).from(operationalCorrectiveActions).leftJoin(users, eq(operationalCorrectiveActions.assignedToUserId, users.id)).where(and(eq(operationalCorrectiveActions.tenantId, input.tenantId), eq(operationalCorrectiveActions.companyId, input.companyId))).orderBy(desc(operationalCorrectiveActions.dueAt), desc(operationalCorrectiveActions.updatedAt)).limit(200),
      db.select({ user: users, role: appRoles }).from(tenantUsers).innerJoin(users, eq(tenantUsers.userId, users.id)).leftJoin(appRoles, eq(tenantUsers.roleId, appRoles.id)).where(and(eq(tenantUsers.tenantId, input.tenantId), eq(tenantUsers.companyId, input.companyId), eq(tenantUsers.status, "active"))).orderBy(users.name),
      db.select().from(branches).where(and(eq(branches.tenantId, input.tenantId), eq(branches.companyId, input.companyId), eq(branches.isActive, true))).orderBy(branches.nameAr),
      db.select().from(operationalKpis).where(and(eq(operationalKpis.tenantId, input.tenantId), eq(operationalKpis.companyId, input.companyId), eq(operationalKpis.isActive, true))).orderBy(operationalKpis.nameAr),
      db.select().from(operationalSlaPolicies).where(and(eq(operationalSlaPolicies.tenantId, input.tenantId), eq(operationalSlaPolicies.companyId, input.companyId), eq(operationalSlaPolicies.isActive, true))).orderBy(operationalSlaPolicies.priority),
    ]);
    const openTasks = tasks.filter(({ task }) => !["completed", "cancelled"].includes(task.status));
    const overdueTasks = openTasks.filter(({ task }) => task.dueAt && task.dueAt.getTime() < Date.now());
    const criticalTasks = openTasks.filter(({ task }) => task.priority === "critical");
    const criticalIssues = issues.filter(({ issue }) => issue.severity === "critical" && !["resolved", "closed"].includes(issue.status));
    const blockedTasks = openTasks.filter(({ task }) => ["blocked", "waiting", "escalated"].includes(task.status));
    const completed = tasks.filter(({ task }) => task.status === "completed").length;
    return { roleCode, tasks, issues, requests, correctiveActions: actions, members, branches: branchRows, kpis, slaPolicies, metrics: { openTasks: openTasks.length, overdueTasks: overdueTasks.length, criticalTasks: criticalTasks.length, completedToday: completed, completionRate: tasks.length ? Math.round((completed / tasks.length) * 100) : 0, openIssues: issues.filter(({ issue }) => !["resolved", "closed"].includes(issue.status)).length, criticalIssues: criticalIssues.length, openRequests: requests.filter(({ request }) => !["completed", "cancelled"].includes(request.status)).length, blockedTasks: blockedTasks.length }, intervention: [...criticalTasks.slice(0, 3).map(({ task }) => ({ type: "critical_task", title: task.title, id: task.id })), ...criticalIssues.slice(0, 3).map(({ issue }) => ({ type: "critical_issue", title: issue.title, id: issue.id })), ...blockedTasks.slice(0, 3).map(({ task }) => ({ type: "blocked_task", title: task.title, id: task.id }))] };
  }),
  createTask: protectedProcedure.input(scopeInput.extend({ title: z.string().trim().min(2).max(255), description: z.string().trim().max(10000).optional(), priority: z.enum(priorities).default("normal"), department: z.string().trim().max(128).optional(), branchId: z.number().int().positive().optional(), assignedToUserId: z.number().int().positive().optional(), dueAt: z.string().datetime().optional(), instructions: z.string().trim().max(10000).optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const result = await db.insert(operationalTasks).values({ tenantId: input.tenantId, companyId: input.companyId, title: input.title, description: input.description || null, priority: input.priority, department: input.department || null, branchId: input.branchId || null, assignedToUserId: input.assignedToUserId || null, createdByUserId: ctx.user.id, dueAt: dateValue(input.dueAt), instructions: input.instructions || null, status: input.assignedToUserId ? "assigned" : "new" }); const id = Number(result[0].insertId); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "operational_task", entityId: id, action: "created", description: "تم إنشاء مهمة تشغيلية." }); return { id }; }),
  updateTask: protectedProcedure.input(scopeInput.extend({ taskId: z.number().int().positive(), status: z.enum(taskStatuses).optional(), assignedToUserId: z.number().int().positive().nullable().optional(), dueAt: z.string().datetime().nullable().optional(), escalationReason: z.string().trim().max(5000).optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const [task] = await db.select().from(operationalTasks).where(and(eq(operationalTasks.id, input.taskId), eq(operationalTasks.tenantId, input.tenantId), eq(operationalTasks.companyId, input.companyId))).limit(1); if (!task) throw new TRPCError({ code: "NOT_FOUND", message: "المهمة التشغيلية غير موجودة ضمن نطاق الشركة." }); await db.update(operationalTasks).set({ status: input.status ?? task.status, assignedToUserId: input.assignedToUserId === undefined ? task.assignedToUserId : input.assignedToUserId, dueAt: input.dueAt === undefined ? task.dueAt : dateValue(input.dueAt ?? undefined), escalationReason: input.escalationReason ?? task.escalationReason, lastUpdatedAt: new Date() }).where(eq(operationalTasks.id, task.id)); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "operational_task", entityId: task.id, action: "updated", description: input.status === "escalated" ? "تم تصعيد المهمة التشغيلية." : "تم تحديث المهمة التشغيلية." }); return { updated: true } as const; }),
  createIssue: protectedProcedure.input(scopeInput.extend({ title: z.string().trim().min(2).max(255), description: z.string().trim().min(2).max(15000), severity: z.enum(severities).default("medium"), department: z.string().trim().max(128).optional(), branchId: z.number().int().positive().optional(), assignedToUserId: z.number().int().positive().optional(), resolutionDueAt: z.string().datetime().optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const result = await db.insert(operationalIssues).values({ tenantId: input.tenantId, companyId: input.companyId, title: input.title, description: input.description, severity: input.severity, department: input.department || null, branchId: input.branchId || null, assignedToUserId: input.assignedToUserId || null, resolutionDueAt: dateValue(input.resolutionDueAt), status: input.assignedToUserId ? "assigned" : "new", createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "operational_issue", entityId: id, action: "created", description: input.severity === "critical" ? "تم تسجيل مشكلة تشغيلية حرجة." : "تم تسجيل مشكلة تشغيلية." }); return { id }; }),
  updateIssue: protectedProcedure.input(scopeInput.extend({ issueId: z.number().int().positive(), status: z.enum(issueStatuses).optional(), rootCause: z.string().trim().max(10000).optional(), immediateAction: z.string().trim().max(10000).optional(), correctiveAction: z.string().trim().max(10000).optional(), preventiveAction: z.string().trim().max(10000).optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const [issue] = await db.select().from(operationalIssues).where(and(eq(operationalIssues.id, input.issueId), eq(operationalIssues.tenantId, input.tenantId), eq(operationalIssues.companyId, input.companyId))).limit(1); if (!issue) throw new TRPCError({ code: "NOT_FOUND", message: "المشكلة التشغيلية غير موجودة ضمن نطاق الشركة." }); await db.update(operationalIssues).set({ status: input.status ?? issue.status, rootCause: input.rootCause ?? issue.rootCause, immediateAction: input.immediateAction ?? issue.immediateAction, correctiveAction: input.correctiveAction ?? issue.correctiveAction, preventiveAction: input.preventiveAction ?? issue.preventiveAction }).where(eq(operationalIssues.id, issue.id)); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "operational_issue", entityId: issue.id, action: "updated", description: "تم تحديث المشكلة والتحليل الجذري." }); return { updated: true } as const; }),
  createCorrectiveAction: protectedProcedure.input(scopeInput.extend({ issueId: z.number().int().positive(), title: z.string().trim().min(2).max(255), description: z.string().trim().max(10000).optional(), assignedToUserId: z.number().int().positive().optional(), dueAt: z.string().datetime().optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const [issue] = await db.select({ id: operationalIssues.id }).from(operationalIssues).where(and(eq(operationalIssues.id, input.issueId), eq(operationalIssues.tenantId, input.tenantId), eq(operationalIssues.companyId, input.companyId))).limit(1); if (!issue) throw new TRPCError({ code: "NOT_FOUND", message: "لا يمكن إنشاء إجراء تصحيحي لمشكلة خارج نطاق الشركة." }); const result = await db.insert(operationalCorrectiveActions).values({ tenantId: input.tenantId, companyId: input.companyId, issueId: input.issueId, title: input.title, description: input.description || null, assignedToUserId: input.assignedToUserId || null, dueAt: dateValue(input.dueAt), createdByUserId: ctx.user.id }); const id = Number(result[0].insertId); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "operational_corrective_action", entityId: id, action: "created", description: "تم إنشاء إجراء تصحيحي." }); return { id }; }),
  createRequest: protectedProcedure.input(scopeInput.extend({ requestType: z.string().trim().min(2).max(64), description: z.string().trim().min(2).max(10000), priority: z.enum(priorities).default("normal"), department: z.string().trim().max(128).optional(), branchId: z.number().int().positive().optional(), assignedToUserId: z.number().int().positive().optional(), requiresApproval: z.boolean().default(false), dueAt: z.string().datetime().optional() })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const result = await db.insert(operationalRequests).values({ tenantId: input.tenantId, companyId: input.companyId, requestType: input.requestType, description: input.description, priority: input.priority, department: input.department || null, branchId: input.branchId || null, requestedByUserId: ctx.user.id, assignedToUserId: input.assignedToUserId || null, requiresApproval: input.requiresApproval, status: input.requiresApproval ? "review" : input.assignedToUserId ? "assigned" : "request", dueAt: dateValue(input.dueAt) }); const id = Number(result[0].insertId); await log(db, { ...input, actorUserId: ctx.user.id, entityType: "operational_request", entityId: id, action: "created", description: "تم تسجيل طلب داخلي تشغيلي." }); return { id }; }),
  upsertKpi: protectedProcedure.input(scopeInput.extend({ code: z.string().trim().min(2).max(64), nameAr: z.string().trim().min(2).max(255), targetValue: z.string().regex(/^\\d+(\\.\\d{1,6})?$/).optional(), isActive: z.boolean().default(true) })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const [existing] = await db.select().from(operationalKpis).where(and(eq(operationalKpis.tenantId, input.tenantId), eq(operationalKpis.companyId, input.companyId), eq(operationalKpis.code, input.code))).limit(1); if (existing) { await db.update(operationalKpis).set({ nameAr: input.nameAr, targetValue: input.targetValue ?? null, isActive: input.isActive }).where(eq(operationalKpis.id, existing.id)); return { id: existing.id, updated: true } as const; } const result = await db.insert(operationalKpis).values({ tenantId: input.tenantId, companyId: input.companyId, code: input.code, nameAr: input.nameAr, targetValue: input.targetValue ?? null, isActive: input.isActive }); return { id: Number(result[0].insertId), updated: false } as const; }),
  upsertSlaPolicy: protectedProcedure.input(scopeInput.extend({ priority: z.enum(priorities), responseMinutes: z.number().int().positive(), resolutionMinutes: z.number().int().positive(), department: z.string().trim().max(128).optional(), isActive: z.boolean().default(true) })).mutation(async ({ ctx, input }) => { const { db } = await requireActor(ctx.user.id, input); const existingRows = await db.select().from(operationalSlaPolicies).where(and(eq(operationalSlaPolicies.tenantId, input.tenantId), eq(operationalSlaPolicies.companyId, input.companyId), eq(operationalSlaPolicies.priority, input.priority), input.department ? eq(operationalSlaPolicies.department, input.department) : eq(operationalSlaPolicies.department, ""))).limit(1); const existing = existingRows[0]; if (existing) { await db.update(operationalSlaPolicies).set({ responseMinutes: input.responseMinutes, resolutionMinutes: input.resolutionMinutes, isActive: input.isActive }).where(eq(operationalSlaPolicies.id, existing.id)); return { id: existing.id, updated: true } as const; } const result = await db.insert(operationalSlaPolicies).values({ tenantId: input.tenantId, companyId: input.companyId, priority: input.priority, responseMinutes: input.responseMinutes, resolutionMinutes: input.resolutionMinutes, department: input.department || null, isActive: input.isActive }); return { id: Number(result[0].insertId), updated: false } as const; }),
  generateSummary: protectedProcedure.input(scopeInput).query(async ({ ctx, input }) => { const { db, roleCode } = await requireActor(ctx.user.id, input); const [tasks, issues, requests, actions] = await Promise.all([db.select().from(operationalTasks).where(and(eq(operationalTasks.tenantId, input.tenantId), eq(operationalTasks.companyId, input.companyId))), db.select().from(operationalIssues).where(and(eq(operationalIssues.tenantId, input.tenantId), eq(operationalIssues.companyId, input.companyId))), db.select().from(operationalRequests).where(and(eq(operationalRequests.tenantId, input.tenantId), eq(operationalRequests.companyId, input.companyId))), db.select().from(operationalCorrectiveActions).where(and(eq(operationalCorrectiveActions.tenantId, input.tenantId), eq(operationalCorrectiveActions.companyId, input.companyId)))]); return { roleCode, generatedAt: new Date(), overallStatus: issues.some((item) => item.severity === "critical" && !["resolved", "closed"].includes(item.status)) ? "يحتاج تدخلاً" : tasks.some((item) => ["blocked", "escalated"].includes(item.status)) ? "توجد تعثرات" : "مستقر", completedTasks: tasks.filter((item) => item.status === "completed").length, overdueTasks: tasks.filter((item) => item.dueAt && item.dueAt.getTime() < Date.now() && !["completed", "cancelled"].includes(item.status)).length, criticalIssues: issues.filter((item) => item.severity === "critical" && !["resolved", "closed"].includes(item.status)).length, pendingRequests: requests.filter((item) => !["completed", "cancelled"].includes(item.status)).length, overdueCorrectiveActions: actions.filter((item) => item.dueAt && item.dueAt.getTime() < Date.now() && !["completed", "verified"].includes(item.status)).length, recommendedActions: ["مراجعة المهام الحرجة والمتأخرة", "تحديد مسؤول للطلبات غير المسندة", "متابعة الإجراءات التصحيحية المتأخرة"] }; }),
  report: protectedProcedure.input(scopeInput).query(async ({ ctx, input }) => { const { db, roleCode } = await requireActor(ctx.user.id, input); const [tasks, issues, requests, actions] = await Promise.all([db.select().from(operationalTasks).where(and(eq(operationalTasks.tenantId, input.tenantId), eq(operationalTasks.companyId, input.companyId))), db.select().from(operationalIssues).where(and(eq(operationalIssues.tenantId, input.tenantId), eq(operationalIssues.companyId, input.companyId))), db.select().from(operationalRequests).where(and(eq(operationalRequests.tenantId, input.tenantId), eq(operationalRequests.companyId, input.companyId))), db.select().from(operationalCorrectiveActions).where(and(eq(operationalCorrectiveActions.tenantId, input.tenantId), eq(operationalCorrectiveActions.companyId, input.companyId)))]); return { roleCode, totals: { tasks: tasks.length, overdueTasks: tasks.filter((item) => item.dueAt && item.dueAt.getTime() < Date.now() && !["completed", "cancelled"].includes(item.status)).length, criticalTasks: tasks.filter((item) => item.priority === "critical" && !["completed", "cancelled"].includes(item.status)).length, issues: issues.length, criticalIssues: issues.filter((item) => item.severity === "critical" && !["resolved", "closed"].includes(item.status)).length, requests: requests.length, pendingRequests: requests.filter((item) => !["completed", "cancelled"].includes(item.status)).length, correctiveActions: actions.length, overdueCorrectiveActions: actions.filter((item) => item.dueAt && item.dueAt.getTime() < Date.now() && !["completed", "verified"].includes(item.status)).length } }; }),
});

export type OperationsControlRouter = typeof operationsControlRouter;
