import { TRPCError } from "@trpc/server";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { appRoles, approvalPolicies, permissions, rolePermissions, tenantUsers } from "../../drizzle/schema";
import { getDb } from "../db";
import { defaultPermissions, defaultRoles, rolePermissionCodes } from "../finance/rbac";
import { protectedProcedure, router } from "../_core/trpc";

const scopeInput = z.object({ tenantId: z.number().int().positive(), companyId: z.number().int().positive() });

async function accessTenant(userId: number, tenantId: number) { const db = await getDb(); if (!db) throw new TRPCError({ code: "SERVICE_UNAVAILABLE" }); const member = await db.select({ id: tenantUsers.id }).from(tenantUsers).where(and(eq(tenantUsers.userId, userId), eq(tenantUsers.tenantId, tenantId), eq(tenantUsers.status, "active"))).limit(1); if (!member[0]) throw new TRPCError({ code: "FORBIDDEN" }); return db; }
async function requireAdmin(userId: number, input: z.infer<typeof scopeInput>) { const db = await getDb(); if (!db) throw new TRPCError({ code: "SERVICE_UNAVAILABLE" }); const member = await db.select({ roleCode: appRoles.code }).from(tenantUsers).innerJoin(appRoles, eq(appRoles.id, tenantUsers.roleId)).where(and(eq(tenantUsers.userId, userId), eq(tenantUsers.tenantId, input.tenantId), eq(tenantUsers.companyId, input.companyId), eq(tenantUsers.status, "active"))).limit(1); if (!member[0] || !["company_admin", "super_admin"].includes(member[0].roleCode)) throw new TRPCError({ code: "FORBIDDEN", message: "إدارة الأدوار متاحة لمدير النظام داخل الشركة الحالية فقط." }); return db; }

export const rbacRouter = router({
  seedDefaults: protectedProcedure.input(scopeInput).mutation(async ({ ctx, input }) => { const db = await accessTenant(ctx.user.id, input.tenantId); return db.transaction(async (tx) => { for (const permission of defaultPermissions) { const existing = await tx.select({ id: permissions.id }).from(permissions).where(eq(permissions.code, permission.code)).limit(1); if (!existing[0]) await tx.insert(permissions).values(permission); } for (const role of defaultRoles) { const existing = await tx.select({ id: appRoles.id }).from(appRoles).where(and(eq(appRoles.tenantId, input.tenantId), eq(appRoles.code, role.code))).limit(1); if (!existing[0]) await tx.insert(appRoles).values({ tenantId: input.tenantId, ...role, isSystem: true, isActive: true }); } const roleRows = await tx.select().from(appRoles).where(eq(appRoles.tenantId, input.tenantId)); const permissionRows = await tx.select().from(permissions); const roleByCode = new Map(roleRows.map((role) => [role.code, role])); const permissionByCode = new Map(permissionRows.map((permission) => [permission.code, permission])); for (const [roleCode, permissionCodes] of Object.entries(rolePermissionCodes)) { const role = roleByCode.get(roleCode); if (!role) continue; for (const permissionCode of permissionCodes) { const permission = permissionByCode.get(permissionCode); if (!permission) continue; const exists = await tx.select({ id: rolePermissions.id }).from(rolePermissions).where(and(eq(rolePermissions.tenantId, input.tenantId), eq(rolePermissions.roleId, role.id), eq(rolePermissions.permissionId, permission.id))).limit(1); if (!exists[0]) await tx.insert(rolePermissions).values({ tenantId: input.tenantId, roleId: role.id, permissionId: permission.id }); } } const [invoicePolicy] = await tx.select({ id: approvalPolicies.id }).from(approvalPolicies).where(and(eq(approvalPolicies.tenantId, input.tenantId), eq(approvalPolicies.companyId, input.companyId), eq(approvalPolicies.documentType, "invoice"))).limit(1); if (!invoicePolicy) await tx.insert(approvalPolicies).values({ tenantId: input.tenantId, companyId: input.companyId, documentType: "invoice", minAmount: "50000.000000", requiredPermission: "invoice.approve", preventSelfApproval: true }); return { roleCount: defaultRoles.length, permissionCount: defaultPermissions.length }; }); }),
  matrix: protectedProcedure.input(scopeInput).query(async ({ ctx, input }) => { const db = await requireAdmin(ctx.user.id, input); const [roles, permissionRows, policies, links] = await Promise.all([db.select().from(appRoles).where(eq(appRoles.tenantId, input.tenantId)), db.select().from(permissions), db.select().from(approvalPolicies).where(and(eq(approvalPolicies.tenantId, input.tenantId), eq(approvalPolicies.companyId, input.companyId))), db.select().from(rolePermissions).where(eq(rolePermissions.tenantId, input.tenantId))]); return { roles, permissions: permissionRows, policies, links }; }),
  createCustomRole: protectedProcedure.input(scopeInput.extend({ nameAr: z.string().trim().min(2).max(128), code: z.string().trim().regex(/^[a-z][a-z0-9_]{2,63}$/) })).mutation(async ({ ctx, input }) => { const db = await requireAdmin(ctx.user.id, input); const existing = await db.select({ id: appRoles.id }).from(appRoles).where(and(eq(appRoles.tenantId, input.tenantId), eq(appRoles.code, input.code))).limit(1); if (existing[0]) throw new TRPCError({ code: "CONFLICT", message: "رمز الدور مستخدم داخل الشركة." }); const result = await db.insert(appRoles).values({ tenantId: input.tenantId, code: input.code, nameAr: input.nameAr, isSystem: false, isActive: true }); return { id: Number(result[0].insertId) }; }),
  cloneRole: protectedProcedure.input(scopeInput.extend({ sourceRoleId: z.number().int().positive(), nameAr: z.string().trim().min(2).max(128), code: z.string().trim().regex(/^[a-z][a-z0-9_]{2,63}$/) })).mutation(async ({ ctx, input }) => { const db = await requireAdmin(ctx.user.id, input); const source = await db.select().from(appRoles).where(and(eq(appRoles.id, input.sourceRoleId), eq(appRoles.tenantId, input.tenantId))).limit(1); if (!source[0]) throw new TRPCError({ code: "NOT_FOUND", message: "الدور المصدر غير موجود." }); const existing = await db.select({ id: appRoles.id }).from(appRoles).where(and(eq(appRoles.tenantId, input.tenantId), eq(appRoles.code, input.code))).limit(1); if (existing[0]) throw new TRPCError({ code: "CONFLICT", message: "رمز الدور مستخدم داخل الشركة." }); return db.transaction(async (tx) => { const result = await tx.insert(appRoles).values({ tenantId: input.tenantId, code: input.code, nameAr: input.nameAr, isSystem: false, isActive: true }); const newRoleId = Number(result[0].insertId); const sourceLinks = await tx.select().from(rolePermissions).where(and(eq(rolePermissions.tenantId, input.tenantId), eq(rolePermissions.roleId, source[0].id))); if (sourceLinks.length) await tx.insert(rolePermissions).values(sourceLinks.map((link) => ({ tenantId: input.tenantId, roleId: newRoleId, permissionId: link.permissionId }))); return { id: newRoleId, copiedPermissions: sourceLinks.length }; }); }),
  deactivateCustomRole: protectedProcedure.input(scopeInput.extend({ roleId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await requireAdmin(ctx.user.id, input); const role = await db.select().from(appRoles).where(and(eq(appRoles.id, input.roleId), eq(appRoles.tenantId, input.tenantId))).limit(1); if (!role[0]) throw new TRPCError({ code: "NOT_FOUND", message: "الدور غير موجود." }); if (role[0].isSystem) throw new TRPCError({ code: "FORBIDDEN", message: "لا يمكن تعطيل دور نظامي؛ أنشئ Custom Role عند الحاجة." }); await db.update(appRoles).set({ isActive: false }).where(eq(appRoles.id, input.roleId)); return { updated: true }; }),
  updateRolePermissions: protectedProcedure.input(scopeInput.extend({ roleId: z.number().int().positive(), permissionIds: z.array(z.number().int().positive()).max(200) })).mutation(async ({ ctx, input }) => { const db = await requireAdmin(ctx.user.id, input); const role = await db.select().from(appRoles).where(and(eq(appRoles.id, input.roleId), eq(appRoles.tenantId, input.tenantId))).limit(1); if (!role[0]) throw new TRPCError({ code: "NOT_FOUND", message: "الدور غير موجود." }); return db.transaction(async (tx) => { await tx.delete(rolePermissions).where(and(eq(rolePermissions.tenantId, input.tenantId), eq(rolePermissions.roleId, input.roleId))); if (input.permissionIds.length) await tx.insert(rolePermissions).values(input.permissionIds.map((permissionId) => ({ tenantId: input.tenantId, roleId: input.roleId, permissionId }))); return { updated: true, count: input.permissionIds.length }; }); }),
});
