CREATE TABLE IF NOT EXISTS `zatcaEgsUnits` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenantId` int NOT NULL,
  `companyId` int NOT NULL,
  `branchId` int NULL,
  `environment` enum('simulation','production') NOT NULL DEFAULT 'simulation',
  `deviceName` varchar(255) NOT NULL,
  `serialNumber` varchar(128) NOT NULL,
  `invoiceType` enum('standard','simplified','both') NOT NULL DEFAULT 'both',
  `status` enum('draft','onboarding','active','suspended','retired') NOT NULL DEFAULT 'draft',
  `csrStatus` enum('not_started','pending','issued','failed','expired') NOT NULL DEFAULT 'not_started',
  `complianceCsidStatus` enum('not_started','pending','issued','failed','expired') NOT NULL DEFAULT 'not_started',
  `complianceCheckStatus` enum('not_started','pending','issued','failed','expired') NOT NULL DEFAULT 'not_started',
  `productionCsidStatus` enum('not_started','pending','issued','failed','expired') NOT NULL DEFAULT 'not_started',
  `connectionStatus` enum('not_configured','connected','degraded','failed') NOT NULL DEFAULT 'not_configured',
  `csrPemEncrypted` text NULL,
  `privateKeyEncrypted` text NULL,
  `certificateExpiresAt` timestamp NULL,
  `lastSuccessfulConnection` timestamp NULL,
  `createdByUserId` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `zatca_egs_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`),
  CONSTRAINT `zatca_egs_company_fk` FOREIGN KEY (`companyId`) REFERENCES `companies` (`id`),
  CONSTRAINT `zatca_egs_branch_fk` FOREIGN KEY (`branchId`) REFERENCES `branches` (`id`),
  CONSTRAINT `zatca_egs_created_by_fk` FOREIGN KEY (`createdByUserId`) REFERENCES `users` (`id`),
  UNIQUE KEY `zatca_egs_company_env_serial_unique` (`tenantId`,`companyId`,`environment`,`serialNumber`),
  KEY `zatca_egs_scope_idx` (`tenantId`,`companyId`,`environment`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `zatcaCredentials` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenantId` int NOT NULL,
  `companyId` int NOT NULL,
  `egsId` int NOT NULL,
  `environment` enum('simulation','production') NOT NULL,
  `credentialType` enum('compliance_csid','production_csid') NOT NULL,
  `requestId` varchar(128) NULL,
  `encryptedBinarySecurityToken` text NULL,
  `encryptedSecret` text NULL,
  `issuedAt` timestamp NULL,
  `expiresAt` timestamp NULL,
  `status` enum('active','expired','revoked') NOT NULL DEFAULT 'active',
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  CONSTRAINT `zatca_credentials_tenant_fk` FOREIGN KEY (`tenantId`) REFERENCES `tenants` (`id`),
  CONSTRAINT `zatca_credentials_company_fk` FOREIGN KEY (`companyId`) REFERENCES `companies` (`id`),
  CONSTRAINT `zatca_credentials_egs_fk` FOREIGN KEY (`egsId`) REFERENCES `zatcaEgsUnits` (`id`),
  KEY `zatca_credentials_scope_idx` (`tenantId`,`companyId`,`egsId`,`environment`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
