export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  authMode: process.env.AUTH_MODE === "local" ? "local" : "manus",
  localAdminEmail: process.env.LOCAL_ADMIN_EMAIL?.trim().toLowerCase() ?? "",
  localAdminPassword: process.env.LOCAL_ADMIN_PASSWORD ?? "",
  storageMode: process.env.STORAGE_MODE === "local" ? "local" : "forge",
  localStoragePath: process.env.LOCAL_STORAGE_PATH ?? "/data/qayd-storage",
  publicAppUrl: process.env.PUBLIC_APP_URL?.replace(/\/+$/, "") ?? "",
  zatcaSimulationBaseUrl: process.env.ZATCA_SIMULATION_BASE_URL?.replace(/\/+$/, "") ?? "https://gw-fatoora.zatca.gov.sa",
  zatcaSimulationCompliancePath: process.env.ZATCA_SIMULATION_COMPLIANCE_PATH ?? "/e-invoicing/simulation/compliance",
  zatcaSimulationComplianceChecksPath: process.env.ZATCA_SIMULATION_COMPLIANCE_CHECKS_PATH ?? "/e-invoicing/simulation/compliance/invoices",
  zatcaSimulationProductionCsidPath: process.env.ZATCA_SIMULATION_PRODUCTION_CSID_PATH ?? "/e-invoicing/simulation/production/csids",
  zatcaSimulationClearancePath: process.env.ZATCA_SIMULATION_CLEARANCE_PATH ?? "/e-invoicing/simulation/invoices/clearance/single",
  zatcaSimulationReportingPath: process.env.ZATCA_SIMULATION_REPORTING_PATH ?? "/e-invoicing/simulation/invoices/reporting/single",
  zatcaApiVersion: process.env.ZATCA_API_VERSION ?? "V2",
};
