export const defaultRoles = [
  { code: "super_admin", nameAr: "مدير المنصة" },
  { code: "company_admin", nameAr: "مدير النظام" },
  { code: "finance_manager", nameAr: "المدير المالي ورئيس الحسابات" },
  { code: "cfo", nameAr: "المدير المالي ورئيس الحسابات" },
  { code: "accountant", nameAr: "محاسب" },
  { code: "external_auditor", nameAr: "محاسب قانوني" },
  { code: "general_manager", nameAr: "مدير عام" },
  { code: "sales", nameAr: "مشرف المبيعات" },
  { code: "sales_rep", nameAr: "ممثل مبيعات" },
  { code: "read_only", nameAr: "قراءة فقط" },
  { code: "ceo_assistant", nameAr: "المساعد الإداري" },
  { code: "operations_manager", nameAr: "مدير العمليات" },
  { code: "executive_assistant", nameAr: "مساعد المدير التنفيذي" },
] as const;

export const defaultPermissions = [
  { code: "invoice.create", module: "sales", descriptionAr: "إنشاء فواتير" },
  { code: "invoice.approve", module: "sales", descriptionAr: "اعتماد فواتير" },
  { code: "journal.create", module: "accounting", descriptionAr: "إنشاء قيود" },
  { code: "journal.post", module: "accounting", descriptionAr: "ترحيل قيود" },
  { code: "payment.create", module: "treasury", descriptionAr: "إنشاء تحصيلات ومدفوعات" },
  { code: "payment.approve", module: "treasury", descriptionAr: "اعتماد تحصيلات ومدفوعات" },
  { code: "report.view", module: "reporting", descriptionAr: "عرض التقارير" },
  { code: "company.manage", module: "setup", descriptionAr: "إدارة إعدادات الشركة" },
  { code: "document.manage", module: "documents", descriptionAr: "إدارة المستندات" },
  { code: "crm.customer.create", module: "crm", descriptionAr: "تسجيل الشركات والعملاء المحتملين" },
  { code: "crm.customer.view.assigned", module: "crm", descriptionAr: "عرض العملاء المسندين لممثل المبيعات" },
  { code: "crm.lead.view.assigned", module: "crm", descriptionAr: "عرض العملاء المحتملين المسندين" },
  { code: "crm.lead.create", module: "crm", descriptionAr: "إنشاء عميل محتمل" },
  { code: "crm.lead.edit.assigned", module: "crm", descriptionAr: "تعديل عميل محتمل مسند" },
  { code: "crm.opportunity.create", module: "crm", descriptionAr: "إنشاء فرصة بيعية" },
  { code: "crm.opportunity.edit.assigned", module: "crm", descriptionAr: "تعديل فرصة مسندة" },
  { code: "crm.activity.create", module: "crm", descriptionAr: "إضافة نشاط ومتابعة بيعية" },
  { code: "crm.task.create", module: "crm", descriptionAr: "إنشاء مهمة متابعة" },
  { code: "crm.visit.create", module: "crm", descriptionAr: "تسجيل زيارات وتواصل المبيعات" },
  { code: "quotation.create.assigned", module: "sales", descriptionAr: "إنشاء عرض سعر للعميل المسند" },
  { code: "quotation.send.assigned", module: "sales", descriptionAr: "إرسال عرض سعر مسند" },
  { code: "discount.request", module: "sales", descriptionAr: "طلب اعتماد خصم" },
  { code: "sales.performance.view", module: "sales", descriptionAr: "عرض الأداء الشخصي" },
  { code: "sales.commission.view", module: "sales", descriptionAr: "عرض العمولات المرتبطة بممثل المبيعات" },
  { code: "sales.representatives.view.all", module: "sales", descriptionAr: "عرض جميع ممثلي المبيعات" },
  { code: "sales.leads.view.all", module: "sales", descriptionAr: "عرض جميع العملاء المحتملين" },
  { code: "sales.lead.assign", module: "sales", descriptionAr: "توزيع وإعادة توزيع العملاء المحتملين" },
  { code: "sales.customers.view.all", module: "sales", descriptionAr: "عرض جميع عملاء قسم المبيعات" },
  { code: "sales.customers.reassign", module: "sales", descriptionAr: "إعادة توزيع العملاء" },
  { code: "sales.opportunities.view.all", module: "sales", descriptionAr: "عرض جميع الفرص البيعية" },
  { code: "sales.opportunities.reassign", module: "sales", descriptionAr: "إعادة توزيع الفرص البيعية" },
  { code: "sales.quotations.review", module: "sales", descriptionAr: "مراجعة عروض الأسعار" },
  { code: "sales.followups.view.all", module: "sales", descriptionAr: "عرض جميع المتابعات والمهام" },
  { code: "sales.tasks.assign", module: "sales", descriptionAr: "إسناد مهام لممثلي المبيعات" },
  { code: "sales.activities.view.all", module: "sales", descriptionAr: "عرض جميع أنشطة المبيعات" },
  { code: "sales.performance.view.all", module: "sales", descriptionAr: "عرض أداء جميع ممثلي المبيعات" },
  { code: "sales.forecast.view", module: "sales", descriptionAr: "عرض توقعات المبيعات" },
  { code: "sales.reports.view", module: "sales", descriptionAr: "عرض تقارير المبيعات" },
  { code: "audit.closing.view", module: "audit", descriptionAr: "عرض حالة الإقفال" },
  { code: "audit.closing.note", module: "audit", descriptionAr: "إضافة ملاحظة تدقيق على الإقفال" },
  { code: "audit.period.reopen_request", module: "audit", descriptionAr: "طلب إعادة فتح فترة للمراجعة" },
  { code: "audit.report.manage", module: "audit", descriptionAr: "إعداد تقرير المراجع النهائي" },
  { code: "audit.signoff.create", module: "audit", descriptionAr: "توقيع تقرير المراجعة رقمياً" },
  { code: "audit.independence.declare", module: "audit", descriptionAr: "تسجيل إقرار الاستقلالية" },
  { code: "audit.reopen.approve", module: "audit", descriptionAr: "اعتماد أو رفض طلب إعادة فتح فترة" },
  { code: "executive.dashboard.view", module: "executive", descriptionAr: "عرض لوحة المتابعة التنفيذية" },
  { code: "executive.followup.create", module: "executive", descriptionAr: "تسجيل ومتابعة التكليفات التنفيذية" },
  { code: "executive.alert.view", module: "executive", descriptionAr: "عرض التنبيهات التشغيلية الموجهة للإدارة" },
  { code: "office.coordination.manage", module: "office", descriptionAr: "تنسيق أعمال المكتب والتوجيهات الإدارية" },
  { code: "accounting.approve", module: "accounting", descriptionAr: "مراجعة واعتماد القيود المحاسبية" },
  { code: "accounting.reverse", module: "accounting", descriptionAr: "إنشاء عكس أو تعديل محاسبي موثق" },
  { code: "expense.approve", module: "operations", descriptionAr: "مراجعة واعتماد المصروفات" },
  { code: "reconciliation.approve", module: "treasury", descriptionAr: "اعتماد التسويات البنكية" },
  { code: "period.manage", module: "accounting", descriptionAr: "إدارة الفترات والإقفالات المالية" },
  { code: "chart.manage", module: "accounting", descriptionAr: "إدارة دليل الحسابات ومراكز التكلفة" },
  { code: "financial.analysis.view", module: "reporting", descriptionAr: "عرض التحليل المالي والتدفق النقدي" },
  { code: "operations.dashboard.view", module: "operations", descriptionAr: "عرض لوحة مدير العمليات" },
  { code: "operations.tasks.view.all", module: "operations", descriptionAr: "عرض جميع المهام التشغيلية ضمن النطاق" },
  { code: "operations.task.create", module: "operations", descriptionAr: "إنشاء مهمة تشغيلية" },
  { code: "operations.task.assign", module: "operations", descriptionAr: "إسناد وإعادة إسناد مهمة تشغيلية" },
  { code: "operations.task.close", module: "operations", descriptionAr: "إغلاق أو إعادة فتح مهمة تشغيلية" },
  { code: "operations.issue.create", module: "operations", descriptionAr: "إنشاء مشكلة أو حادث تشغيلي" },
  { code: "operations.issue.manage", module: "operations", descriptionAr: "إدارة المشكلة والتحليل الجذري" },
  { code: "operations.issue.escalate", module: "operations", descriptionAr: "تصعيد مشكلة تشغيلية" },
  { code: "operations.corrective_action.manage", module: "operations", descriptionAr: "إنشاء وإدارة إجراء تصحيحي" },
  { code: "operations.request.view", module: "operations", descriptionAr: "عرض الطلبات الداخلية" },
  { code: "operations.request.approve", module: "operations", descriptionAr: "اعتماد الطلبات التشغيلية المسموحة" },
  { code: "operations.branch.view", module: "operations", descriptionAr: "عرض أداء الفروع" },
  { code: "operations.department.view", module: "operations", descriptionAr: "عرض أداء الأقسام" },
  { code: "operations.kpi.view", module: "operations", descriptionAr: "عرض مؤشرات الأداء التشغيلي" },
  { code: "operations.kpi.manage", module: "operations", descriptionAr: "تخصيص مؤشرات الأداء التشغيلي" },
  { code: "operations.sla.manage", module: "operations", descriptionAr: "إدارة سياسات SLA التشغيلية" },
  { code: "operations.reports.view", module: "operations", descriptionAr: "عرض التقارير التشغيلية" },
  { code: "operations.summary.generate", module: "operations", descriptionAr: "إنشاء ملخص تشغيلي للإدارة التنفيذية" },
  { code: "executive.calendar.manage", module: "executive", descriptionAr: "إدارة تقويم المدير التنفيذي" },
  { code: "executive.meeting.create", module: "executive", descriptionAr: "إنشاء الاجتماعات التنفيذية" },
  { code: "executive.meeting.brief", module: "executive", descriptionAr: "إعداد موجز الاجتماع التنفيذي" },
  { code: "executive.meeting.minutes", module: "executive", descriptionAr: "إدارة محاضر الاجتماعات التنفيذية" },
  { code: "executive.requests.view", module: "executive", descriptionAr: "عرض طلبات المدير التنفيذي" },
  { code: "executive.tasks.manage", module: "executive", descriptionAr: "إدارة المهام التنفيذية والمتابعات" },
  { code: "executive.decisions.view", module: "executive", descriptionAr: "عرض قرارات المدير التنفيذي" },
  { code: "executive.decisions.track", module: "executive", descriptionAr: "متابعة تنفيذ قرارات المدير التنفيذي" },
  { code: "executive.documents.view.allowed", module: "executive", descriptionAr: "عرض المستندات التنفيذية المسموحة" },
  { code: "executive.summaries.view", module: "executive", descriptionAr: "عرض الملخصات التنفيذية" },
  { code: "executive.daily_brief.generate", module: "executive", descriptionAr: "إنشاء الموجز اليومي للمدير التنفيذي" },
  { code: "executive.weekly_brief.generate", module: "executive", descriptionAr: "إنشاء الموجز الأسبوعي للمدير التنفيذي" },
  { code: "executive.reminder.send", module: "executive", descriptionAr: "إرسال تذكيرات داخلية تنفيذية" },
  { code: "executive.delegation.manage", module: "executive", descriptionAr: "إدارة التفويضات التنفيذية المؤقتة" },
  { code: "executive.command_center.view", module: "executive", descriptionAr: "عرض مركز القيادة التنفيذي" },
  { code: "executive.company_sales_summary.view", module: "executive", descriptionAr: "عرض ملخص أداء المبيعات" },
  { code: "executive.company_financial_summary.view", module: "executive", descriptionAr: "عرض الملخص المالي التنفيذي" },
  { code: "executive.company_operations_summary.view", module: "executive", descriptionAr: "عرض ملخص الأداء التشغيلي" },
  { code: "executive.kpis.view", module: "executive", descriptionAr: "عرض مؤشرات الشركة التنفيذية" },
  { code: "executive.branches_summary.view", module: "executive", descriptionAr: "عرض ملخصات الفروع" },
  { code: "executive.reports.view", module: "executive", descriptionAr: "عرض التقارير التنفيذية" },
  { code: "executive.risks.view", module: "executive", descriptionAr: "عرض المخاطر التنفيذية" },
  { code: "executive.opportunities.view", module: "executive", descriptionAr: "عرض الفرص التنفيذية" },
  { code: "executive.approval.decide", module: "executive", descriptionAr: "اتخاذ قرار على طلب اعتماد تنفيذي" },
  { code: "executive.decision.create", module: "executive", descriptionAr: "إنشاء قرار تنفيذي" },
  { code: "executive.task.assign", module: "executive", descriptionAr: "إسناد مهمة تنفيذية" },
  { code: "executive.ai.use", module: "executive", descriptionAr: "استخدام التحليل التنفيذي الذكي" },
  { code: "executive.report.generate", module: "executive", descriptionAr: "إنشاء تقرير تنفيذي" },
  { code: "executive.approval_policy.manage", module: "executive", descriptionAr: "إدارة مصفوفة حدود الاعتماد" },
  { code: "admin.dashboard.view", module: "settings", descriptionAr: "عرض لوحة مدير النظام" },
  { code: "admin.users.manage", module: "settings", descriptionAr: "إدارة مستخدمي الشركة" },
  { code: "admin.user.invite", module: "settings", descriptionAr: "دعوة مستخدم إلى الشركة" },
  { code: "admin.user.suspend", module: "settings", descriptionAr: "إيقاف مستخدم وإلغاء وصوله" },
  { code: "admin.roles.manage", module: "settings", descriptionAr: "إدارة الأدوار المخصصة" },
  { code: "admin.permissions.manage", module: "settings", descriptionAr: "تعديل صلاحيات الأدوار" },
  { code: "admin.company_profile.manage", module: "settings", descriptionAr: "إدارة ملف الشركة" },
  { code: "admin.branches.manage", module: "settings", descriptionAr: "إدارة الفروع" },
  { code: "admin.settings.manage", module: "settings", descriptionAr: "إدارة الإعدادات العامة" },
  { code: "admin.integrations.manage", module: "settings", descriptionAr: "إدارة التكاملات" },
  { code: "admin.security.view", module: "settings", descriptionAr: "عرض مركز الأمان" },
  { code: "admin.session.revoke", module: "settings", descriptionAr: "إنهاء جلسة مستخدم" },
  { code: "admin.audit.view", module: "settings", descriptionAr: "عرض سجل التدقيق الإداري" },
  { code: "admin.subscription.view", module: "settings", descriptionAr: "عرض الاشتراك والاستخدام" },
  { code: "admin.subscription.manage", module: "settings", descriptionAr: "إدارة اشتراك الشركة" },
  { code: "admin.data_export.request", module: "settings", descriptionAr: "طلب تصدير بيانات الشركة" },
  { code: "admin.support_access.grant", module: "settings", descriptionAr: "منح وصول دعم مؤقت" },
] as const;

export const rolePermissionCodes: Record<string, string[]> = {
  super_admin: defaultPermissions.map((permission) => permission.code),
  company_admin: ["admin.dashboard.view", "admin.users.manage", "admin.user.invite", "admin.user.suspend", "admin.roles.manage", "admin.permissions.manage", "admin.company_profile.manage", "admin.branches.manage", "admin.settings.manage", "admin.integrations.manage", "admin.security.view", "admin.session.revoke", "admin.audit.view", "admin.subscription.view", "admin.subscription.manage", "admin.data_export.request", "admin.support_access.grant"],
  finance_manager: ["invoice.create", "invoice.approve", "journal.create", "journal.post", "payment.create", "payment.approve", "report.view", "document.manage", "accounting.approve", "accounting.reverse", "expense.approve", "reconciliation.approve", "period.manage", "chart.manage", "financial.analysis.view"],
  accountant: ["invoice.create", "journal.create", "payment.create", "report.view", "document.manage"],
  cfo: ["invoice.create", "invoice.approve", "journal.create", "journal.post", "payment.create", "payment.approve", "report.view", "document.manage", "accounting.approve", "accounting.reverse", "expense.approve", "reconciliation.approve", "period.manage", "chart.manage", "financial.analysis.view", "audit.reopen.approve"],
  external_auditor: ["report.view", "document.manage", "audit.closing.view", "audit.closing.note", "audit.period.reopen_request", "audit.report.manage", "audit.signoff.create", "audit.independence.declare"],
  general_manager: ["invoice.approve", "payment.approve", "report.view", "executive.command_center.view", "executive.company_sales_summary.view", "executive.company_financial_summary.view", "executive.company_operations_summary.view", "executive.kpis.view", "executive.branches_summary.view", "executive.reports.view", "executive.risks.view", "executive.opportunities.view", "executive.approval.decide", "executive.decision.create", "executive.task.assign", "executive.ai.use", "executive.report.generate"],
  sales: ["crm.customer.create", "crm.visit.create", "crm.opportunity.create", "crm.activity.create", "crm.task.create", "quotation.create.assigned", "quotation.send.assigned", "discount.request", "sales.commission.view", "sales.representatives.view.all", "sales.leads.view.all", "sales.lead.assign", "sales.customers.view.all", "sales.customers.reassign", "sales.opportunities.view.all", "sales.opportunities.reassign", "sales.quotations.review", "sales.followups.view.all", "sales.tasks.assign", "sales.activities.view.all", "sales.performance.view.all", "sales.forecast.view", "sales.reports.view"],
  sales_rep: ["crm.customer.create", "crm.customer.view.assigned", "crm.lead.view.assigned", "crm.lead.create", "crm.lead.edit.assigned", "crm.opportunity.create", "crm.opportunity.edit.assigned", "crm.activity.create", "crm.task.create", "crm.visit.create", "quotation.create.assigned", "quotation.send.assigned", "discount.request", "sales.performance.view", "sales.commission.view"],
  read_only: ["report.view"],
  ceo_assistant: ["executive.dashboard.view", "executive.followup.create", "executive.alert.view", "office.coordination.manage"],
  operations_manager: ["operations.dashboard.view", "operations.tasks.view.all", "operations.task.create", "operations.task.assign", "operations.task.close", "operations.issue.create", "operations.issue.manage", "operations.issue.escalate", "operations.corrective_action.manage", "operations.request.view", "operations.request.approve", "operations.branch.view", "operations.department.view", "operations.kpi.view", "operations.kpi.manage", "operations.sla.manage", "operations.reports.view", "operations.summary.generate", "executive.alert.view"],
  executive_assistant: ["executive.dashboard.view", "executive.alert.view", "executive.calendar.manage", "executive.meeting.create", "executive.meeting.brief", "executive.meeting.minutes", "executive.requests.view", "executive.tasks.manage", "executive.decisions.view", "executive.decisions.track", "executive.documents.view.allowed", "executive.summaries.view", "executive.daily_brief.generate", "executive.weekly_brief.generate", "executive.reminder.send"],
};

export function canApproveDocument(initiatorUserId: number, approverUserId: number, preventSelfApproval: boolean) {
  return !preventSelfApproval || initiatorUserId !== approverUserId;
}
