import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Clock3, FileCheck2, ListChecks, Loader2 } from "lucide-react";
import { useMemo } from "react";

const formatDate = (value: Date | string | null | undefined) => value ? new Date(value).toLocaleString("en-CA") : "—";

export function AuditControlEvidence({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const input = useMemo(() => ({ tenantId: tenantId ?? 0, companyId: companyId ?? 0 }), [tenantId, companyId]);
  const dashboard = trpc.audit.dashboard.useQuery(input, { enabled: Boolean(tenantId && companyId) });
  if (!tenantId || !companyId || dashboard.isLoading || dashboard.error || !dashboard.data) return dashboard.isLoading ? <Card className="border-0 shadow-sm rounded-2xl"><CardContent className="p-6"><Loader2 className="h-5 w-5 animate-spin text-[#0b3d3a]" /></CardContent></Card> : null;
  const { periods, closeHistory, entries, reports, signoffs, engagements } = dashboard.data;
  const periodName = (id: number) => periods.find((period) => period.id === id)?.name ?? `الفترة #${id}`;
  return <section className="grid gap-5 xl:grid-cols-[1.1fr_0.9fr]">
    <Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf1f8] text-[#345b95]"><ListChecks className="h-5 w-5" /></div><div><CardTitle className="text-base">تفاصيل القيود حول الإقفال</CardTitle><p className="mt-1 text-sm text-muted-foreground">يعرض السجل القابل للمراجعة القيود قبل وقت الإقفال وبعده، لا مجرد عدّادات.</p></div></div></CardHeader><CardContent className="space-y-4">{periods.map((period) => { const history = closeHistory.filter((event) => event.entityId === period.id); const currentLock = history.find((event) => event.action === "fiscal_period.status_updated") ?? history[0]; const lockAt = period.lockedAt ?? currentLock?.createdAt; const rows = entries.filter((entry) => entry.fiscalPeriodId === period.id); const preClose = lockAt ? rows.filter((entry) => new Date(entry.createdAt) <= new Date(lockAt)) : rows; const postClose = lockAt ? rows.filter((entry) => new Date(entry.createdAt) > new Date(lockAt)) : []; return <div key={period.id} className="rounded-xl border border-[#dce4dd] bg-[#fbfdfb] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-[#2d4438]">{period.name}</p><p className="mt-1 text-xs text-[#66786f]">حالة الإقفال: <span dir="ltr">{period.status}</span> · منفذ الإقفال: {currentLock?.actorName || (period.lockedByUserId ? `مستخدم #${period.lockedByUserId}` : "غير مسجل")}</p><p className="mt-1 text-xs text-[#66786f]">وقت الإقفال: <span dir="ltr">{formatDate(lockAt)}</span></p></div><Badge variant="outline">{period.status}</Badge></div><AdjustmentList title="Pre-Close Adjustments" rows={preClose} empty="لا توجد قيود قبل الإقفال." tone="text-[#285c40]" /><AdjustmentList title="Post-Close Adjustments" rows={postClose} empty="لا توجد قيود بعد الإقفال." tone="text-[#9a6015]" /></div>; })}</CardContent></Card>
    <Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eef6ed] text-[#276542]"><FileCheck2 className="h-5 w-5" /></div><div><CardTitle className="text-base">أدلة التقرير والتوقيع</CardTitle><p className="mt-1 text-sm text-muted-foreground">الفترة المالية ظاهرة ومخزنة صراحةً في التقرير النهائي والتوقيع الرقمي.</p></div></div></CardHeader><CardContent className="space-y-3">{engagements.map((engagement) => <div key={engagement.id} className="rounded-xl border border-[#dce4dd] bg-[#fbfdfb] p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-[#2d4438]">{engagement.engagementName}</p><p className="mt-1 text-xs text-[#64756c]">الفترة: {periodName(engagement.fiscalPeriodId)} · الاستقلالية: {engagement.isIndependenceDeclared ? "مُعلنة" : "بانتظار الإقرار"}</p></div><Badge variant="outline">{engagement.status}</Badge></div>{reports.filter((report) => report.engagementId === engagement.id).map((report) => { const signoff = signoffs.find((item) => item.reportId === report.id); return <div key={report.id} className="mt-3 rounded-lg bg-white p-3 text-xs"><p className="font-medium">Audit Final Report · {periodName(report.fiscalPeriodId)}</p><p className="mt-1 text-[#64756c]">الرأي: {report.opinionStatus} · {report.isLocked ? "مقفل" : "مسودة قابلة للمراجعة"}</p>{signoff ? <p className="mt-2 flex items-center gap-1 text-[#285c40]"><Clock3 className="h-3.5 w-3.5" />توقيع {signoff.auditorName} · الفترة: {periodName(signoff.fiscalPeriodId)} · {formatDate(signoff.signedAt)}</p> : <p className="mt-2 text-[#9a6015]">لا يمكن الإقفال النهائي حتى إضافة التوقيع الرقمي.</p>}</div>; })}</div>)}</CardContent></Card>
  </section>;
}

function AdjustmentList({ title, rows, empty, tone }: { title: string; rows: Array<{ id: number; entryNumber: string; entryDate: Date | string; description: string | null; status: string; createdAt: Date | string }>; empty: string; tone: string }) {
  return <div className="mt-4"><p className={`text-xs font-bold ${tone}`}>{title}</p>{rows.length ? <div className="mt-2 overflow-x-auto rounded-lg border border-[#e5ece7]"><table className="w-full min-w-[500px] text-right text-xs"><thead className="bg-[#f4f8f5] text-[#63736a]"><tr><th className="p-2 font-medium">القيد</th><th className="p-2 font-medium">التاريخ</th><th className="p-2 font-medium">الوصف</th><th className="p-2 font-medium">سُجل في</th></tr></thead><tbody>{rows.map((entry) => <tr key={entry.id} className="border-t border-[#edf1ee]"><td className="p-2 font-medium" dir="ltr">{entry.entryNumber}</td><td className="p-2" dir="ltr">{new Date(entry.entryDate).toLocaleDateString("en-CA")}</td><td className="max-w-52 truncate p-2">{entry.description ?? "—"}</td><td className="p-2" dir="ltr">{formatDate(entry.createdAt)}</td></tr>)}</tbody></table></div> : <p className="mt-2 rounded-lg bg-white p-2 text-xs text-[#78867f]">{empty}</p>}</div>;
}
