import React from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { accountStatementBalance, type FinancialStatementAccount } from "../../../shared/financialStatements";
import { deriveFinancialReportsState } from "../../../shared/financialReportsState";
import { BarChart3, Landmark, Loader2, SearchCheck } from "lucide-react";
import { useMemo, useState } from "react";

type AccountRow = FinancialStatementAccount & { id: number; code: string; nameAr: string };
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "SAR", minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);
const balance = accountStatementBalance;

export function DetailedFinancialReports({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const input = useMemo(() => ({ tenantId: tenantId ?? 0, companyId: companyId ?? 0 }), [tenantId, companyId]); const [selectedAccountId, setSelectedAccountId] = useState<number | null>(null);
  const report = trpc.operations.trialBalance.useQuery(input, { enabled: Boolean(tenantId && companyId) });
  const ledger = trpc.operations.ledger.useQuery({ ...input, accountId: selectedAccountId ?? undefined }, { enabled: Boolean(tenantId && companyId && selectedAccountId) });
  if (!tenantId || !companyId) return null;
  if (report.isLoading) return <Card className="mt-5 border-0 shadow-sm rounded-2xl"><CardContent className="p-7"><Loader2 className="h-5 w-5 animate-spin text-[#0b3d3a]" /></CardContent></Card>;
  if (report.error) return <Card className="mt-5 border border-[#f2d5d0] shadow-sm rounded-2xl"><CardContent className="p-7"><p className="font-semibold text-[#8a3c32]">تعذر تحميل التقارير المالية</p><p className="mt-2 text-sm text-[#765953]">{report.error.message} لم تُعرض أرصدة صفرية بديلة.</p></CardContent></Card>;
  const rows = (report.data ?? []) as AccountRow[];
  const financialState = deriveFinancialReportsState(rows);
  const { revenues, expenses, assets, liabilities, equity, revenueTotal, expenseTotal, assetsTotal, liabilitiesTotal, equityTotal, netIncome } = financialState;
  const selectedAccount = rows.find((row) => row.id === selectedAccountId);
  return <section className="mt-5 space-y-5"><div className="grid gap-5 xl:grid-cols-2"><StatementCard title="قائمة الدخل التفصيلية" subtitle="اضغط على اسم الحساب لفتح قيوده المرحلة المصدرية." icon={<BarChart3 className="h-5 w-5" />} sections={[{ label: "الإيرادات والدخل الآخر", rows: revenues, tone: "text-[#17653c]", total: revenueTotal }, { label: "التكاليف والمصروفات", rows: expenses, tone: "text-[#9a5a15]", total: expenseTotal }]} footerLabel="صافي النتيجة" footerValue={netIncome} onAccountSelect={setSelectedAccountId} />
  <StatementCard title="المركز المالي التفصيلي" subtitle="اضغط على اسم الحساب لفتح قيوده المرحلة المصدرية." icon={<Landmark className="h-5 w-5" />} sections={[{ label: "الأصول", rows: assets, tone: "text-[#235e86]", total: assetsTotal }, { label: "الالتزامات", rows: liabilities, tone: "text-[#9a4d37]", total: liabilitiesTotal }, { label: "حقوق الملكية", rows: equity, tone: "text-[#66529d]", total: equityTotal }]} footerLabel="إجمالي الالتزامات وحقوق الملكية" footerValue={liabilitiesTotal + equityTotal} onAccountSelect={setSelectedAccountId} /></div>
  {selectedAccountId && <Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eff5fa] text-[#2b6594]"><SearchCheck className="h-5 w-5" /></div><div><CardTitle className="text-base">تتبع الأستاذ العام: {selectedAccount?.nameAr}</CardTitle><p className="mt-1 text-sm text-muted-foreground">قيود مرحلة مصدرية للحساب <span dir="ltr">{selectedAccount?.code}</span> ضمن القائمة المالية.</p></div></div></CardHeader><CardContent>{ledger.isLoading ? <Loader2 className="h-5 w-5 animate-spin text-[#0b3d3a]" /> : ledger.data?.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-right text-xs"><thead className="border-b text-[#66776e]"><tr><th className="p-3">التاريخ</th><th className="p-3">القيد</th><th className="p-3">الوصف</th><th className="p-3">مدين</th><th className="p-3">دائن</th></tr></thead><tbody>{ledger.data.map((line, index) => <tr key={`${line.entryNumber}-${index}`} className="border-b last:border-0"><td className="p-3" dir="ltr">{new Date(line.entryDate).toLocaleDateString("en-CA")}</td><td className="p-3 font-medium" dir="ltr">{line.entryNumber}</td><td className="p-3">{line.description ?? "—"}</td><td className="p-3" dir="ltr">{money(Number(line.debit))}</td><td className="p-3" dir="ltr">{money(Number(line.credit))}</td></tr>)}</tbody></table></div> : <p className="rounded-lg bg-[#f7f9f7] p-3 text-sm text-[#6d7c73]">لا توجد قيود مرحلة لهذا الحساب بعد.</p>}</CardContent></Card>}</section>;
}

function StatementCard({ title, subtitle, icon, sections, footerLabel, footerValue, onAccountSelect }: { title: string; subtitle: string; icon: React.ReactNode; sections: Array<{ label: string; rows: AccountRow[]; tone: string; total: number }>; footerLabel: string; footerValue: number; onAccountSelect: (accountId: number) => void }) {
  return <Card className="overflow-hidden border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf5ef] text-[#0b3d3a]">{icon}</div><div><CardTitle className="text-base">{title}</CardTitle><p className="mt-1 text-sm leading-6 text-muted-foreground">{subtitle}</p></div></div></CardHeader><CardContent className="space-y-4">{sections.map((section) => <div key={section.label}><div className="flex items-center justify-between"><p className={`text-sm font-bold ${section.tone}`}>{section.label}</p><Badge variant="outline" dir="ltr">{money(section.total)}</Badge></div>{section.rows.length ? <div className="mt-2 overflow-x-auto rounded-xl border border-[#e5ebe6]"><table className="w-full min-w-[440px] text-right text-xs"><thead className="bg-[#f5f8f5] text-[#68786f]"><tr><th className="p-2 font-medium">الحساب</th><th className="p-2 font-medium">مدين</th><th className="p-2 font-medium">دائن</th><th className="p-2 font-medium">الرصيد</th></tr></thead><tbody>{section.rows.map((row) => <tr key={row.code} className="border-t border-[#edf1ee]"><td className="p-2"><button type="button" className="font-medium text-[#0b3d3a] underline-offset-2 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#0b3d3a]" onClick={() => onAccountSelect(row.id)}>{row.nameAr}</button><span className="mr-2 text-[#7a8880]" dir="ltr">{row.code}</span></td><td className="p-2" dir="ltr">{money(Number(row.debit))}</td><td className="p-2" dir="ltr">{money(Number(row.credit))}</td><td className="p-2 font-semibold" dir="ltr">{money(balance(row))}</td></tr>)}</tbody></table></div> : <p className="mt-2 rounded-lg bg-[#f7f9f7] p-3 text-xs text-[#738077]">لا توجد أرصدة مرحلة ضمن هذا التصنيف.</p>}</div>)}<div className="flex items-center justify-between rounded-xl bg-[#0b3d3a] px-4 py-3 text-sm font-bold text-white"><span>{footerLabel}</span><span dir="ltr">{money(footerValue)}</span></div></CardContent></Card>;
}
