import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { BriefcaseBusiness, FolderKanban, Loader2, Plus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type CostCenterRecord = { id: number; code: string; nameAr: string; isActive: boolean };
type ProjectRecord = { id: number; code: string; nameAr: string; status: "active" | "on_hold" | "closed" };

function CostCenterRow({ item, tenantId, companyId, onSaved }: { item: CostCenterRecord; tenantId: number; companyId: number; onSaved: () => Promise<void> }) {
  const [nameAr, setNameAr] = useState(item.nameAr); const [isActive, setIsActive] = useState(item.isActive);
  const update = trpc.finance.updateCostCenter.useMutation({ onSuccess: async () => { toast.success("تم حفظ مركز التكلفة."); await onSaved(); }, onError: (error) => toast.error(error.message) });
  return <div className="rounded-xl border border-[#dce4dd] bg-[#fbfdfb] p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-[#718079]" dir="ltr">{item.code}</p><Input className="mt-1 h-9 max-w-xs" value={nameAr} onChange={(event) => setNameAr(event.target.value)} /></div><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-xs text-[#52645a]"><input type="checkbox" checked={isActive} onChange={(event) => setIsActive(event.target.checked)} className="h-4 w-4 accent-[#0b3d3a]" />نشط</label><Button size="sm" disabled={!nameAr.trim() || update.isPending} onClick={() => update.mutate({ tenantId, companyId, costCenterId: item.id, nameAr: nameAr.trim(), isActive })}>{update.isPending && <Loader2 className="ml-1 h-3.5 w-3.5 animate-spin" />}حفظ</Button></div></div></div>;
}

function ProjectRow({ item, tenantId, companyId, onSaved }: { item: ProjectRecord; tenantId: number; companyId: number; onSaved: () => Promise<void> }) {
  const [nameAr, setNameAr] = useState(item.nameAr); const [status, setStatus] = useState<ProjectRecord["status"]>(item.status);
  const update = trpc.finance.updateProject.useMutation({ onSuccess: async () => { toast.success("تم حفظ المشروع."); await onSaved(); }, onError: (error) => toast.error(error.message) });
  return <div className="rounded-xl border border-[#dce4dd] bg-[#fbfdfb] p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-[#718079]" dir="ltr">{item.code}</p><Input className="mt-1 h-9 max-w-xs" value={nameAr} onChange={(event) => setNameAr(event.target.value)} /></div><div className="flex items-center gap-3"><select value={status} onChange={(event) => setStatus(event.target.value as ProjectRecord["status"])} className="h-9 rounded-md border border-[#cfd9d2] bg-white px-2 text-xs"><option value="active">نشط</option><option value="on_hold">معلّق</option><option value="closed">مغلق</option></select><Button size="sm" disabled={!nameAr.trim() || update.isPending} onClick={() => update.mutate({ tenantId, companyId, projectId: item.id, nameAr: nameAr.trim(), status })}>{update.isPending && <Loader2 className="ml-1 h-3.5 w-3.5 animate-spin" />}حفظ</Button></div></div></div>;
}

export function DimensionsManager({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const enabled = Boolean(tenantId && companyId); const input = { tenantId: tenantId ?? 0, companyId: companyId ?? 0 };
  const data = trpc.finance.setupData.useQuery(input, { enabled }); const utils = trpc.useUtils();
  const [centerCode, setCenterCode] = useState(""); const [centerName, setCenterName] = useState(""); const [projectCode, setProjectCode] = useState(""); const [projectName, setProjectName] = useState("");
  const refresh = async () => { await utils.finance.setupData.invalidate(input); };
  const addCenter = trpc.finance.addCostCenter.useMutation({ onSuccess: async () => { setCenterCode(""); setCenterName(""); toast.success("تمت إضافة مركز التكلفة."); await refresh(); }, onError: (error) => toast.error(error.message) });
  const addProject = trpc.finance.addProject.useMutation({ onSuccess: async () => { setProjectCode(""); setProjectName(""); toast.success("تمت إضافة المشروع."); await refresh(); }, onError: (error) => toast.error(error.message) });
  if (!enabled) return null;
  return <section className="mt-5 grid gap-5 xl:grid-cols-2"><Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e7f3eb] text-[#0b3d3a]"><BriefcaseBusiness className="h-5 w-5" /></div><div><CardTitle className="text-base">مراكز التكلفة</CardTitle><p className="mt-1 text-sm text-muted-foreground">تتبع التكلفة في المصروفات والعمليات على مستوى الشركة الموحدة.</p></div></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Input value={centerCode} onChange={(event) => setCenterCode(event.target.value)} placeholder="رمز المركز" dir="ltr" /><Input value={centerName} onChange={(event) => setCenterName(event.target.value)} placeholder="اسم مركز التكلفة" /></div><Button variant="outline" disabled={!centerCode.trim() || !centerName.trim() || addCenter.isPending} onClick={() => addCenter.mutate({ ...input, code: centerCode.trim(), nameAr: centerName.trim() })}><Plus className="ml-1 h-4 w-4" />إضافة مركز تكلفة</Button><div className="space-y-2">{data.data?.costCenters.length ? data.data.costCenters.map((item) => <CostCenterRow key={item.id} item={item} tenantId={input.tenantId} companyId={input.companyId} onSaved={refresh} />) : <p className="rounded-xl bg-[#f7f9f7] p-3 text-sm text-[#68766d]">لا توجد مراكز تكلفة بعد.</p>}</div></CardContent></Card><Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf1f8] text-[#385b93]"><FolderKanban className="h-5 w-5" /></div><div><CardTitle className="text-base">المشاريع</CardTitle><p className="mt-1 text-sm text-muted-foreground">حالات واضحة للمشروع: نشط، معلّق، أو مغلق.</p></div></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Input value={projectCode} onChange={(event) => setProjectCode(event.target.value)} placeholder="رمز المشروع" dir="ltr" /><Input value={projectName} onChange={(event) => setProjectName(event.target.value)} placeholder="اسم المشروع" /></div><Button variant="outline" disabled={!projectCode.trim() || !projectName.trim() || addProject.isPending} onClick={() => addProject.mutate({ ...input, code: projectCode.trim(), nameAr: projectName.trim() })}><Plus className="ml-1 h-4 w-4" />إضافة مشروع</Button><div className="space-y-2">{data.data?.projects.length ? data.data.projects.map((item) => <ProjectRow key={item.id} item={item} tenantId={input.tenantId} companyId={input.companyId} onSaved={refresh} />) : <p className="rounded-xl bg-[#f7f9f7] p-3 text-sm text-[#68766d]">لا توجد مشاريع بعد.</p>}</div></CardContent></Card></section>;
}
