import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { Archive, FileLock2, Loader2, ShieldAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const classifications = ["vat", "zakat", "supplier", "customer", "audit", "financial_statement", "bank", "zatca", "contract", "miscellaneous"] as const;
const labels: Record<(typeof classifications)[number], string> = { vat: "VAT", zakat: "زكاة", supplier: "مورد", customer: "عميل", audit: "مراجعة", financial_statement: "قوائم مالية", bank: "بنك", zatca: "ZATCA", contract: "عقد", miscellaneous: "متنوع" };
const formatDate = (value: Date | string | null) => value ? new Date(value).toLocaleDateString("en-CA") : "غير محدد";

export function DocumentRetentionManager({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const input = useMemo(() => ({ tenantId: tenantId ?? 0, companyId: companyId ?? 0 }), [tenantId, companyId]); const enabled = Boolean(tenantId && companyId); const [classification, setClassification] = useState<(typeof classifications)[number]>("vat"); const [years, setYears] = useState("7"); const [preventDeletion, setPreventDeletion] = useState(true); const utils = trpc.useUtils();
  const data = trpc.documents.retentionDashboard.useQuery(input, { enabled }); const refresh = () => utils.documents.retentionDashboard.invalidate(input);
  const savePolicy = trpc.documents.saveRetentionPolicy.useMutation({ onSuccess: async () => { toast.success("حُفظت سياسة الاحتفاظ."); await refresh(); }, onError: (error) => toast.error(error.message) });
  const apply = trpc.documents.applyRetentionPolicy.useMutation({ onSuccess: async () => { toast.success("طُبقت سياسة الاحتفاظ على المستند."); await refresh(); }, onError: (error) => toast.error(error.message) });
  const archive = trpc.documents.archiveDocument.useMutation({ onSuccess: async () => { toast.success("أُرشف المستند مع بقاء أثره وسجلّه."); await refresh(); }, onError: (error) => toast.error(error.message) });
  const hold = trpc.documents.setDocumentLegalHold.useMutation({ onSuccess: async () => { toast.success("حُدثت حالة الحجز القانوني."); await refresh(); }, onError: (error) => toast.error(error.message) });
  if (!enabled || data.isLoading) return data.isLoading ? <Card className="mt-5 border-0 shadow-sm rounded-2xl"><CardContent className="p-6"><Loader2 className="h-5 w-5 animate-spin text-[#0b3d3a]" /></CardContent></Card> : null;
  if (data.error) return <Card className="mt-5 border border-[#f2d4ce] shadow-sm rounded-2xl"><CardContent className="p-6 text-sm text-[#873b31]">تعذر تحميل سياسات الاحتفاظ: {data.error.message}</CardContent></Card>;
  const dashboard = data.data; if (!dashboard) return null;
  return <section className="mt-5 grid gap-5 xl:grid-cols-[0.8fr_1.2fr]"><Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fff1e7] text-[#9b5d19]"><FileLock2 className="h-5 w-5" /></div><div><CardTitle className="text-base">سياسة احتفاظ المستندات</CardTitle><p className="mt-1 text-sm leading-6 text-muted-foreground">تحدد مدة الاحتفاظ ومنع الحذف لكل تصنيف، وتطبق على المستندات الجديدة أو المحددة يدوياً.</p></div></div></CardHeader><CardContent className="space-y-3"><label className="text-sm font-medium text-[#44564d]">التصنيف<select className="mt-2 h-10 w-full rounded-md border border-[#cfd9d2] bg-white px-3 text-sm" value={classification} onChange={(event) => setClassification(event.target.value as typeof classification)}>{classifications.map((item) => <option key={item} value={item}>{labels[item]}</option>)}</select></label><label className="text-sm font-medium text-[#44564d]">مدة الاحتفاظ بالسنوات<Input className="mt-2" inputMode="numeric" dir="ltr" value={years} onChange={(event) => setYears(event.target.value)} /></label><label className="flex items-center justify-between gap-3 rounded-xl bg-[#f6f9f6] p-3 text-sm font-medium text-[#3e5147]"><span>منع الحذف المادي</span><Switch checked={preventDeletion} onCheckedChange={setPreventDeletion} /></label><Button className="w-full bg-[#0b3d3a] hover:bg-[#082f2d]" disabled={!/^\d+$/.test(years) || Number(years) < 1 || savePolicy.isPending} onClick={() => savePolicy.mutate({ ...input, classification, retentionYears: Number(years), preventDeletion, isActive: true })}>حفظ السياسة</Button><div className="space-y-2 pt-2">{dashboard.policies.map((policy) => <div key={policy.id} className="rounded-lg border border-[#e3e9e4] bg-[#fbfdfb] p-3 text-xs"><div className="flex justify-between"><span className="font-medium">{labels[policy.classification as keyof typeof labels] ?? policy.classification}</span><Badge variant="outline">{policy.isActive ? "نشطة" : "متوقفة"}</Badge></div><p className="mt-1 text-[#708077]">{policy.retentionYears} سنوات · {policy.preventDeletion ? "الحذف محظور" : "الحذف غير محظور بالسياسة"}</p></div>)}</div></CardContent></Card>
  <Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eef5ed] text-[#28633e]"><Archive className="h-5 w-5" /></div><div><CardTitle className="text-base">أرشفة المستندات وحالتها</CardTitle><p className="mt-1 text-sm leading-6 text-muted-foreground">لا يوفر النظام حذفاً مادياً للمستندات. الحجز القانوني يوقف الأرشفة ويمنع الحذف.</p></div></div></CardHeader><CardContent className="space-y-3">{dashboard.documents.length ? dashboard.documents.map((document) => { const policies = dashboard.policies.filter((policy) => policy.classification === document.classification && policy.isActive); return <div key={document.id} className="rounded-xl border border-[#e1e8e2] bg-[#fbfdfb] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium text-[#2b4035]">{document.filename}</p><p className="mt-1 text-xs text-[#74817a]">{labels[document.classification as keyof typeof labels] ?? document.classification} · الاحتفاظ حتى: <span dir="ltr">{formatDate(document.retentionUntil)}</span></p></div><div className="flex gap-2"><Badge variant="outline">{document.retentionStatus}</Badge>{document.isLegalHold && <Badge className="bg-[#fff0ee] text-[#983f33]"><ShieldAlert className="ml-1 h-3 w-3" />حجز</Badge>}</div></div><div className="mt-3 flex flex-wrap gap-2">{!document.retentionPolicyId && policies.map((policy) => <Button key={policy.id} size="sm" variant="outline" disabled={apply.isPending} onClick={() => apply.mutate({ ...input, documentId: document.id, policyId: policy.id })}>تطبيق سياسة {policy.retentionYears} سنوات</Button>)}{document.retentionStatus === "active" && !document.isLegalHold && <Button size="sm" variant="outline" disabled={archive.isPending} onClick={() => archive.mutate({ ...input, documentId: document.id })}>أرشفة</Button>}<Button size="sm" variant={document.isLegalHold ? "outline" : "secondary"} disabled={hold.isPending} onClick={() => hold.mutate({ ...input, documentId: document.id, isLegalHold: !document.isLegalHold })}>{document.isLegalHold ? "رفع الحجز" : "وضع حجز قانوني"}</Button></div></div>; }) : <p className="rounded-xl bg-[#f7f9f7] p-4 text-sm text-[#6c7a72]">لا توجد مستندات بعد. عند رفع مستند يمكن ربطه بسياسة احتفاظ وأرشفته لاحقاً.</p>}</CardContent></Card></section>;
}
