import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ClipboardCheck, FileBarChart2, Loader2, Plus, Send, ShieldAlert } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const today = new Date().toISOString().slice(0, 10);
const statusLabels: Record<string, string> = { planned: "مخطط", in_progress: "قيد التنفيذ", blocked: "متعثر", completed: "مكتمل", cancelled: "ملغى" };
const priorityLabels: Record<string, string> = { low: "منخفضة", normal: "عادية", high: "عالية", urgent: "عاجلة" };
const reportLabels: Record<string, string> = { draft: "مسودة", submitted: "مرفوع للرئيس التنفيذي", reviewed: "تمت المراجعة" };
const asDate = (value: Date | string) => new Date(value).toISOString().slice(0, 10);

export function ExecutiveCoordinationBoard({ tenantId, companyId, roleCode }: { tenantId?: number; companyId?: number; roleCode?: string | null }) {
  const enabled = Boolean(tenantId && companyId);
  const input = useMemo(() => ({ tenantId: tenantId ?? 0, companyId: companyId ?? 0 }), [tenantId, companyId]);
  const dashboard = trpc.executive.dashboard.useQuery(input, { enabled, retry: false });
  const utils = trpc.useUtils();
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [dueDate, setDueDate] = useState(today); const [priority, setPriority] = useState<"low" | "normal" | "high" | "urgent">("normal"); const [assignedToUserId, setAssignedToUserId] = useState(""); const [filterStatus, setFilterStatus] = useState("all"); const [filterAssignee, setFilterAssignee] = useState("all"); const [filterDueDate, setFilterDueDate] = useState("");
  const [weekStart, setWeekStart] = useState(today); const [weekEnd, setWeekEnd] = useState(today); const [summary, setSummary] = useState(""); const [achievements, setAchievements] = useState(""); const [blockers, setBlockers] = useState(""); const [decisionsNeeded, setDecisionsNeeded] = useState(""); const [nextWeekPlan, setNextWeekPlan] = useState("");
  const refresh = () => void utils.executive.dashboard.invalidate(input);
  const createAssignment = trpc.executive.createAssignment.useMutation({ onSuccess: () => { toast.success("تم حفظ التكليف التنفيذي."); setTitle(""); setDescription(""); refresh(); }, onError: (error) => toast.error(error.message) });
  const updateAssignment = trpc.executive.updateAssignment.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة التكليف."); refresh(); }, onError: (error) => toast.error(error.message) });
  const saveReport = trpc.executive.saveWeeklyReport.useMutation({ onSuccess: () => { toast.success("تم حفظ التقرير الأسبوعي."); setSummary(""); setAchievements(""); setBlockers(""); setDecisionsNeeded(""); setNextWeekPlan(""); refresh(); }, onError: (error) => toast.error(error.message) });
  const reviewReport = trpc.executive.reviewWeeklyReport.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة التقرير."); refresh(); }, onError: (error) => toast.error(error.message) });
  if (!enabled) return null;
  if (dashboard.isLoading) return <Card className="border-0 shadow-sm" dir="rtl"><CardContent className="flex items-center gap-2 p-6 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />تحميل مركز التكليفات والتقارير...</CardContent></Card>;
  if (dashboard.error) return <Card className="border border-[#f1d8d2] shadow-sm" dir="rtl"><CardContent className="flex items-start gap-3 p-6"><ShieldAlert className="h-5 w-5 text-[#a14537]" /><div><p className="font-semibold text-[#77362d]">مركز المتابعة التنفيذية مقيد</p><p className="mt-1 text-sm leading-6 text-[#765953]">{dashboard.error.message}</p></div></CardContent></Card>;
  const data = dashboard.data; if (!data) return null;
  const canCreate = roleCode === "ceo_assistant" || roleCode === "company_admin" || roleCode === "super_admin";
  const canReview = roleCode === "company_admin" || roleCode === "super_admin" || roleCode === "general_manager";
  const visibleAssignments = data.assignments.filter(({ assignment }) => filterStatus === "all" || assignment.status === filterStatus).filter(({ assignment }) => filterAssignee === "all" || String(assignment.assignedToUserId) === filterAssignee).filter(({ assignment }) => !filterDueDate || asDate(assignment.dueDate) <= filterDueDate);
  return <section className="space-y-5" dir="rtl">
    <div className="grid gap-4 lg:grid-cols-2">
      <Card className="border-0 shadow-sm"><CardHeader><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e6f0eb] text-[#0b3d3a]"><ClipboardCheck className="h-5 w-5" /></div><div><CardTitle className="text-base">سجل التكليفات التنفيذي</CardTitle><p className="mt-1 text-sm text-muted-foreground">تابع المسؤول والموعد والحالة والتحديث الأخير.</p></div></div></CardHeader><CardContent className="space-y-3"><div className="grid gap-2 sm:grid-cols-3"><select value={filterStatus} onChange={(event) => setFilterStatus(event.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-xs"><option value="all">كل الحالات</option><option value="planned">مخطط</option><option value="in_progress">قيد التنفيذ</option><option value="blocked">متعثر</option><option value="completed">مكتمل</option><option value="cancelled">ملغى</option></select><select value={filterAssignee} onChange={(event) => setFilterAssignee(event.target.value)} className="h-9 rounded-md border border-input bg-background px-2 text-xs"><option value="all">كل المسؤولين</option>{data.members.map(({ user }) => <option key={user.id} value={user.id}>{user.name || user.email}</option>)}</select><Input type="date" value={filterDueDate} onChange={(event) => setFilterDueDate(event.target.value)} aria-label="حتى تاريخ الاستحقاق" /></div>{visibleAssignments.length ? visibleAssignments.map(({ assignment, assignee }) => <div key={assignment.id} className="rounded-xl border border-[#dce4dd] bg-[#fbfdfb] p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold text-[#263b32]">{assignment.title}</p><p className="mt-1 text-xs text-[#6d7d73]">المسؤول: {assignee.name || assignee.email}</p></div><Badge variant="outline">{statusLabels[assignment.status]}</Badge></div><div className="mt-2 flex flex-wrap gap-2 text-xs text-[#6d7d73]"><span>الاستحقاق: <b dir="ltr">{asDate(assignment.dueDate)}</b></span><span>الأولوية: {priorityLabels[assignment.priority]}</span></div>{assignment.latestUpdate && <p className="mt-2 rounded-lg bg-white p-2 text-sm leading-6 text-[#586a60]">آخر تحديث: {assignment.latestUpdate}</p>}<div className="mt-3 flex flex-wrap gap-2"><select value={assignment.status} onChange={(event) => updateAssignment.mutate({ ...input, assignmentId: assignment.id, status: event.target.value as "planned" | "in_progress" | "blocked" | "completed" | "cancelled" })} className="h-9 rounded-md border border-input bg-background px-2 text-xs"><option value="planned">مخطط</option><option value="in_progress">قيد التنفيذ</option><option value="blocked">متعثر</option><option value="completed">مكتمل</option><option value="cancelled">ملغى</option></select></div></div>) : <p className="rounded-xl bg-[#f7f9f7] p-4 text-sm text-muted-foreground">لا توجد تكليفات مطابقة للمرشحات الحالية.</p>}</CardContent></Card>
      {canCreate && <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">إضافة تكليف جديد</CardTitle><p className="text-sm text-muted-foreground">أنشئ تكليفاً واضحاً بمسؤول وموعد وأولوية.</p></CardHeader><CardContent className="space-y-3"><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="عنوان التكليف" /><Textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="وصف المطلوب والخطوة التالية" /><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs text-muted-foreground">المسؤول<select value={assignedToUserId} onChange={(event) => setAssignedToUserId(event.target.value)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-2 text-sm"><option value="">اختر المسؤول</option>{data.members.map(({ user, membership }) => <option key={membership.id} value={user.id}>{user.name || user.email}</option>)}</select></label><label className="text-xs text-muted-foreground">تاريخ الاستحقاق<Input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} className="mt-1" /></label><label className="text-xs text-muted-foreground">الأولوية<select value={priority} onChange={(event) => setPriority(event.target.value as typeof priority)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-2 text-sm"><option value="low">منخفضة</option><option value="normal">عادية</option><option value="high">عالية</option><option value="urgent">عاجلة</option></select></label></div><Button disabled={!title.trim() || !assignedToUserId || createAssignment.isPending} onClick={() => createAssignment.mutate({ ...input, title: title.trim(), description: description.trim() || undefined, assignedToUserId: Number(assignedToUserId), dueDate, priority })}><Plus className="ml-2 h-4 w-4" />حفظ التكليف</Button></CardContent></Card>}
    </div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card className="border-0 shadow-sm"><CardHeader><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef2f7] text-[#31557e]"><FileBarChart2 className="h-5 w-5" /></div><div><CardTitle className="text-base">التقرير الأسبوعي للرئيس التنفيذي</CardTitle><p className="mt-1 text-sm text-muted-foreground">قالب موحد للإنجازات والمعوقات والقرارات المطلوبة وخطة الأسبوع القادم.</p></div></div></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-muted-foreground">من<Input type="date" value={weekStart} onChange={(event) => setWeekStart(event.target.value)} className="mt-1" /></label><label className="text-xs text-muted-foreground">إلى<Input type="date" value={weekEnd} onChange={(event) => setWeekEnd(event.target.value)} className="mt-1" /></label></div><Textarea value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="الملخص التنفيذي" /><Textarea value={achievements} onChange={(event) => setAchievements(event.target.value)} placeholder="الإنجازات الرئيسية" /><Textarea value={blockers} onChange={(event) => setBlockers(event.target.value)} placeholder="المعوقات والمخاطر" /><Textarea value={decisionsNeeded} onChange={(event) => setDecisionsNeeded(event.target.value)} placeholder="القرارات أو التوجيهات المطلوبة من الرئيس التنفيذي" /><Textarea value={nextWeekPlan} onChange={(event) => setNextWeekPlan(event.target.value)} placeholder="خطة الأسبوع القادم" /><Button disabled={!summary.trim() || saveReport.isPending} onClick={() => saveReport.mutate({ ...input, weekStart, weekEnd, summary: summary.trim(), achievements: achievements.trim() || undefined, blockers: blockers.trim() || undefined, decisionsNeeded: decisionsNeeded.trim() || undefined, nextWeekPlan: nextWeekPlan.trim() || undefined, status: "submitted" })}><Send className="ml-2 h-4 w-4" />رفع التقرير للرئيس التنفيذي</Button></CardContent></Card>
      <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">التقارير المرفوعة</CardTitle><p className="text-sm text-muted-foreground">سجل أسبوعي قابل للمراجعة مع حالة واضحة.</p></CardHeader><CardContent className="space-y-3">{data.reports.length ? data.reports.map(({ report, author }) => <div key={report.id} className="rounded-xl border border-[#dce4dd] bg-[#fbfdfb] p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold text-[#263b32]">أسبوع <span dir="ltr">{asDate(report.weekStart)} — {asDate(report.weekEnd)}</span></p><p className="mt-1 text-xs text-[#6d7d73]">رفع بواسطة: {author.name || author.email}</p></div><Badge variant="outline">{reportLabels[report.status]}</Badge></div><p className="mt-2 text-sm leading-6 text-[#586a60]">{report.summary}</p>{canReview && report.status !== "reviewed" && <Button size="sm" variant="outline" className="mt-3" disabled={reviewReport.isPending} onClick={() => reviewReport.mutate({ ...input, reportId: report.id, status: "reviewed" })}>تأكيد المراجعة</Button>}</div>) : <p className="rounded-xl bg-[#f7f9f7] p-4 text-sm text-muted-foreground">لم تُرفع تقارير أسبوعية بعد.</p>}</CardContent></Card>
    </div>
  </section>;
}
