import { useMemo, useState } from "react";
import { AlertTriangle, BellRing, CalendarDays, CheckCircle2, FileText, Flag, Gavel, Loader2, Mail, Plus, Send, ShieldCheck, Target } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const decisionStatuses: Record<string, string> = { issued: "صادر", assigned: "مسند", in_progress: "قيد التنفيذ", waiting: "بانتظار رد", completed: "مكتمل", closed: "مغلق" };
const priorities: Record<string, string> = { low: "منخفضة", normal: "عادية", high: "عالية", urgent: "عاجلة" };

function Metric({ icon: Icon, label, value }: { icon: typeof Target; label: string; value: number }) {
  return <div className="rounded-2xl border border-[#dce8df] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs text-[#6b7d72]">{label}</span><Icon className="h-4 w-4 text-[#0b3d3a]" /></div><strong className="mt-2 block text-2xl text-[#18332f]" dir="ltr">{value}</strong></div>;
}

export function ExecutiveAssistantWorkspace({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const enabled = Boolean(tenantId && companyId);
  const input = useMemo(() => ({ tenantId: tenantId ?? 0, companyId: companyId ?? 0 }), [tenantId, companyId]);
  const dashboard = trpc.executiveAssistant.dashboard.useQuery(input, { enabled, retry: false });
  const brief = trpc.executiveAssistant.generateBrief.useQuery({ ...input, period: "daily" }, { enabled, retry: false });
  const documents = trpc.executiveAssistant.listDocuments.useQuery(input, { enabled, retry: false });
  const utils = trpc.useUtils();
  const [decisionTitle, setDecisionTitle] = useState("");
  const [decisionRequirement, setDecisionRequirement] = useState("");
  const [decisionDueDate, setDecisionDueDate] = useState("");
  const [requestTitle, setRequestTitle] = useState("");
  const [requestDescription, setRequestDescription] = useState("");
  const [meetingTitle, setMeetingTitle] = useState("");
  const [meetingStartAt, setMeetingStartAt] = useState("");
  const refresh = async () => { await utils.executiveAssistant.dashboard.invalidate(input); await utils.executiveAssistant.generateBrief.invalidate({ ...input, period: "daily" }); };
  const createDecision = trpc.executiveAssistant.createDecision.useMutation({ onSuccess: async () => { toast.success("تم تسجيل القرار للمتابعة دون تغيير القرار الأصلي."); setDecisionTitle(""); setDecisionRequirement(""); setDecisionDueDate(""); await refresh(); }, onError: (error) => toast.error(error.message) });
  const updateDecision = trpc.executiveAssistant.updateDecision.useMutation({ onSuccess: refresh, onError: (error) => toast.error(error.message) });
  const createRequest = trpc.executiveAssistant.createRequest.useMutation({ onSuccess: async () => { toast.success("تم إرسال طلب المدير التنفيذي."); setRequestTitle(""); setRequestDescription(""); await refresh(); }, onError: (error) => toast.error(error.message) });
  const createMeeting = trpc.executiveAssistant.createMeeting.useMutation({ onSuccess: async () => { toast.success("تمت إضافة الاجتماع إلى أجندة المدير التنفيذي."); setMeetingTitle(""); setMeetingStartAt(""); await refresh(); }, onError: (error) => toast.error(error.message) });
  if (!enabled) return null;
  if (dashboard.isLoading) return <Card dir="rtl" className="border-0 shadow-sm"><CardContent className="flex items-center gap-2 p-8 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />تحميل مساحة مساعد المدير التنفيذي...</CardContent></Card>;
  if (dashboard.error) return <Card dir="rtl" className="border border-[#f1d8d2] shadow-sm"><CardContent className="p-6 text-sm text-[#77362d]">مساحة مساعد المدير التنفيذي مقيدة: {dashboard.error.message}</CardContent></Card>;
  const data = dashboard.data;
  if (!data) return null;
  return <section id="executive-assistant-dashboard" dir="rtl" className="space-y-5">
    <Card className="border-0 bg-[#103d3a] text-white shadow-sm"><CardContent className="flex flex-col gap-4 p-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#b7d8c5]">Executive Control Assistant</p><h2 className="mt-2 text-2xl font-bold">مساعد المدير التنفيذي</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/75">ينظم أولويات المدير، يتابع القرارات والاجتماعات والطلبات، ويجهز الموجزات دون اتخاذ القرار أو الاعتماد نيابةً عنه.</p></div><Badge className="w-fit bg-white/15 px-3 py-1.5 text-white hover:bg-white/20">متابعة لا اعتماد</Badge></CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric icon={Gavel} label="قرارات مفتوحة" value={data.metrics.openDecisions} /><Metric icon={CalendarDays} label="اجتماعات قادمة" value={data.metrics.upcomingMeetings} /><Metric icon={Send} label="طلبات مفتوحة" value={data.metrics.openRequests} /><Metric icon={Mail} label="صندوق المدير" value={data.metrics.pendingInbox} /><Metric icon={AlertTriangle} label="مهام متأخرة" value={data.metrics.overdueAssignments} /></div>
    <Card className="border-0 bg-[#f7fbf8] shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Flag className="h-5 w-5 text-[#a14537]" />يحتاج متابعة اليوم</CardTitle><p className="text-sm text-muted-foreground">قرارات أو مهام أو عناصر تنفيذية تتطلب تجهيزاً أو تذكيراً أو تصعيداً للمدير.</p></CardHeader><CardContent className="space-y-2">{data.needsToday.length ? data.needsToday.map((item) => <div key={`${item.type}-${item.id}`} className="flex items-center justify-between rounded-xl border border-[#eadbd6] bg-white p-3"><div><p className="font-semibold text-[#3a2926]">{item.title}</p><p className="mt-1 text-xs text-[#8b716a]">{item.type}</p></div><Badge variant="outline">متابعة</Badge></div>) : <p className="rounded-xl bg-white p-4 text-sm text-muted-foreground">لا توجد عناصر حرجة تحتاج متابعة اليوم.</p>}</CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-[1.25fr_0.75fr]"><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileText className="h-5 w-5 text-[#0b3d3a]" />{brief.data?.headline ?? "Daily CEO Brief"}</CardTitle><p className="text-sm text-muted-foreground">{brief.data?.guardrail}</p></CardHeader><CardContent className="space-y-3">{brief.data?.decisions.slice(0, 5).map((decision) => <div key={decision.id} className="rounded-xl border border-[#dce8df] p-3"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{decision.title}</p><Badge variant="outline">{decisionStatuses[decision.status]}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{decision.requirement}</p></div>)}{!brief.data?.decisions.length && <p className="text-sm text-muted-foreground">لا توجد قرارات مفتوحة في الموجز الحالي.</p>}</CardContent></Card><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-5 w-5 text-[#0b3d3a]" />التفويضات النشطة</CardTitle></CardHeader><CardContent className="space-y-2">{data.delegations.length ? data.delegations.map((delegation) => <div key={delegation.id} className="rounded-xl bg-[#f7f9f7] p-3 text-sm"><p className="font-semibold">{delegation.permission}</p><p className="mt-1 text-xs text-muted-foreground" dir="ltr">{new Date(delegation.startsAt).toLocaleString("en-GB")} – {new Date(delegation.endsAt).toLocaleString("en-GB")}</p></div>) : <p className="text-sm text-muted-foreground">لا توجد تفويضات مؤقتة نشطة. يبقى الدور في نطاق المتابعة فقط.</p>}</CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-3"><Card id="ea-decision-form" className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">قرار تنفيذي</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={decisionTitle} onChange={(e) => setDecisionTitle(e.target.value)} placeholder="عنوان القرار" /><Textarea value={decisionRequirement} onChange={(e) => setDecisionRequirement(e.target.value)} placeholder="المطلوب تنفيذه" /><Input type="date" value={decisionDueDate} onChange={(e) => setDecisionDueDate(e.target.value)} aria-label="الموعد النهائي للقرار" /><Button disabled={!decisionTitle.trim() || !decisionRequirement.trim() || createDecision.isPending} onClick={() => createDecision.mutate({ ...input, title: decisionTitle.trim(), decisionDate: new Date().toISOString().slice(0, 10), requirement: decisionRequirement.trim(), dueDate: decisionDueDate || undefined })}><Plus className="ml-2 h-4 w-4" />تسجيل قرار للمتابعة</Button></CardContent></Card><Card id="ea-request-form" className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">طلب المدير التنفيذي</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={requestTitle} onChange={(e) => setRequestTitle(e.target.value)} placeholder="مثال: اطلب تقريراً من المالية" /><Textarea value={requestDescription} onChange={(e) => setRequestDescription(e.target.value)} placeholder="وصف الطلب والإجراء المطلوب" /><Button variant="outline" disabled={!requestTitle.trim() || !requestDescription.trim() || createRequest.isPending} onClick={() => createRequest.mutate({ ...input, requestType: "request_update", title: requestTitle.trim(), description: requestDescription.trim() })}><Send className="ml-2 h-4 w-4" />إرسال الطلب</Button></CardContent></Card><Card id="ea-meeting-form" className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">اجتماع تنفيذي</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={meetingTitle} onChange={(e) => setMeetingTitle(e.target.value)} placeholder="عنوان الاجتماع" /><Input type="datetime-local" value={meetingStartAt} onChange={(e) => setMeetingStartAt(e.target.value)} aria-label="وقت الاجتماع" /><Button variant="outline" disabled={!meetingTitle.trim() || !meetingStartAt || createMeeting.isPending} onClick={() => createMeeting.mutate({ ...input, title: meetingTitle.trim(), startAt: new Date(meetingStartAt).toISOString() })}><CalendarDays className="ml-2 h-4 w-4" />إضافة إلى التقويم</Button></CardContent></Card></div>
    <Card id="ea-decisions" className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CheckCircle2 className="h-5 w-5 text-[#0b3d3a]" />متابعة القرارات التنفيذية</CardTitle></CardHeader><CardContent className="space-y-2">{data.decisions.slice(0, 12).map(({ decision }) => <div key={decision.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-[#e2e8e3] p-3"><div><p className="font-semibold">{decision.title}</p><p className="mt-1 text-xs text-muted-foreground">{decision.requirement} · إنجاز {decision.completionPercent}%</p></div><select value={decision.status} onChange={(e) => updateDecision.mutate({ ...input, decisionId: decision.id, status: e.target.value as "issued" | "assigned" | "in_progress" | "waiting" | "completed" | "closed" })} className="h-9 rounded-md border border-input bg-background px-2 text-xs" aria-label="حالة القرار">{Object.entries(decisionStatuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>)}{!data.decisions.length && <p className="text-sm text-muted-foreground">لا توجد قرارات مسجلة بعد.</p>}</CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2"><Card id="ea-inbox" className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BellRing className="h-5 w-5 text-[#0b3d3a]" />Executive Inbox</CardTitle><p className="text-sm text-muted-foreground">العناصر التي تحتاج انتباه المدير أو تجهيز المساعد لها.</p></CardHeader><CardContent className="space-y-2">{data.inbox.slice(0, 8).map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl border border-[#e2e8e3] p-3"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.itemType} · {priorities[item.priority]}</p></div><Badge variant={item.priority === "urgent" ? "destructive" : "outline"}>{item.status === "open" ? "مفتوح" : item.status}</Badge></div>)}{!data.inbox.length && <p className="text-sm text-muted-foreground">صندوق المدير فارغ حالياً.</p>}</CardContent></Card><Card id="ea-documents" className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileText className="h-5 w-5 text-[#0b3d3a]" />المستندات التنفيذية</CardTitle><p className="text-sm text-muted-foreground">تظهر فقط الملفات العامة والتنفيذية أو التي تمت مشاركتها مع هذا المستخدم.</p></CardHeader><CardContent className="space-y-2">{documents.data?.slice(0, 8).map(({ executiveDocument }) => <div key={executiveDocument.id} className="flex items-center justify-between rounded-xl border border-[#e2e8e3] p-3"><span className="font-semibold">{executiveDocument.title}</span><Badge variant="outline">{executiveDocument.accessScope}</Badge></div>)}{!documents.data?.length && <p className="text-sm text-muted-foreground">لا توجد مستندات تنفيذية مشتركة حالياً.</p>}</CardContent></Card></div>
    <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-5 w-5 text-[#0b3d3a]" />حدود الدور</CardTitle></CardHeader><CardContent><p className="text-sm leading-7 text-muted-foreground">لا يظهر لهذا الدور دفتر الأستاذ أو القيود التفصيلية أو أرصدة البنوك أو الرواتب أو إعدادات الضرائب وZATCA أو توزيع العملاء أو إدارة المستخدمين والصلاحيات والاشتراكات. أي إجراء باسم المدير التنفيذي يجب أن يرتبط بتفويض مؤقت مسجل، ولا يتيح هذا الدور الاعتماد المالي أو اتخاذ قرار CEO.</p></CardContent></Card>
  </section>;
}
