import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ReceiptText } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { isSelectableCostCenter, isSelectableProject } from "../../../shared/operationalDimensions";

export function ExpenseEntryWithDimensions({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const enabled = Boolean(tenantId && companyId); const input = { tenantId: tenantId ?? 0, companyId: companyId ?? 0 };
  const dimensions = trpc.finance.setupData.useQuery(input, { enabled });
  const [entryNumber, setEntryNumber] = useState(""); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [costCenterId, setCostCenterId] = useState(""); const [projectId, setProjectId] = useState("");
  const expense = trpc.operations.recordExpense.useMutation({ onSuccess: (result) => { toast.success(`سُجل المصروف بالقيد ${result.journalEntryId}.`); setEntryNumber(""); setAmount(""); setDescription(""); setCostCenterId(""); setProjectId(""); }, onError: (error) => toast.error(error.message) });
  if (!enabled) return null;
  const centers = dimensions.data?.costCenters.filter((item) => isSelectableCostCenter(item.isActive)) ?? []; const projects = dimensions.data?.projects.filter((item) => isSelectableProject(item.status)) ?? [];
  return <Card className="mt-5 border border-[#d7e5db] bg-[#fcfefd] shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e7f3eb] text-[#0b3d3a]"><ReceiptText className="h-5 w-5" /></div><div><CardTitle className="text-base">مصروف مع أبعاد تشغيلية</CardTitle><p className="mt-1 text-sm text-muted-foreground">اربط المصروف بمركز تكلفة أو مشروع عند الحاجة؛ لا يقبل النظام مركزاً أو مشروعاً غير نشط.</p></div></div></CardHeader><CardContent className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label className="text-sm font-medium text-[#44564d]">رقم القيد<Input className="mt-2" dir="ltr" value={entryNumber} onChange={(event) => setEntryNumber(event.target.value)} placeholder="EXP-2026-000001" /></label><label className="text-sm font-medium text-[#44564d]">قيمة المصروف<Input className="mt-2" dir="ltr" inputMode="decimal" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0.00" /></label><label className="text-sm font-medium text-[#44564d]">مركز التكلفة<select className="mt-2 h-10 w-full rounded-md border border-[#cfd9d2] bg-white px-3 text-sm" value={costCenterId} onChange={(event) => setCostCenterId(event.target.value)}><option value="">دون مركز تكلفة</option>{centers.map((item) => <option key={item.id} value={item.id}>{item.nameAr} — {item.code}</option>)}</select></label><label className="text-sm font-medium text-[#44564d]">المشروع<select className="mt-2 h-10 w-full rounded-md border border-[#cfd9d2] bg-white px-3 text-sm" value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">دون مشروع</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.nameAr} — {item.code}</option>)}</select></label><label className="text-sm font-medium text-[#44564d] md:col-span-2">وصف المصروف<Textarea className="mt-2" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="وصف واضح للمصروف والغرض التشغيلي" /></label><div className="flex items-end"><Button disabled={!entryNumber.trim() || !amount.trim() || !description.trim() || expense.isPending} className="w-full bg-[#0b3d3a] hover:bg-[#082f2d]" onClick={() => expense.mutate({ ...input, entryNumber: entryNumber.trim(), entryDate: new Date().toISOString().slice(0, 10), amount: amount.trim(), description: description.trim(), costCenterId: costCenterId ? Number(costCenterId) : undefined, projectId: projectId ? Number(projectId) : undefined })}>ترحيل المصروف</Button></div></CardContent></Card>;
}
