import React from "react";
import { ArrowRight, FileCheck2, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { MarketingFooter } from "@/components/MarketingFooter";
import { LEGAL_ENTITY, LEGAL_POLICY_HISTORY, PRODUCT_BRAND } from "../../../shared/productBrand";

type LegalSection = { title: string; body: React.ReactNode };

export function LegalPageLayout({ eyebrow, title, intro, updatedAt, sections }: { eyebrow: string; title: string; intro: string; updatedAt: string; sections: LegalSection[] }) {
  return <div className="min-h-screen bg-[#f6f8f5] text-[#17332f]" dir="rtl">
    <header className="border-b border-[#dce7df] bg-white/95 px-5 py-4 sm:px-8"><div className="mx-auto flex max-w-5xl items-center justify-between gap-4"><Link href="/" className="flex items-center gap-3 rounded-xl focus:outline-none focus-visible:ring-2 focus-visible:ring-[#0b3d3a]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#0b3d3a] text-white"><FileCheck2 className="h-5 w-5" /></span><span><strong className="block text-lg tracking-tight">{PRODUCT_BRAND.bilingual}</strong><span className="block text-[10px] uppercase tracking-[0.14em] text-[#5d776c]">AI Financial Operating System</span></span></Link><Link href="/" className="inline-flex items-center gap-2 rounded-xl border border-[#cbdad1] px-4 py-2 text-sm font-semibold text-[#0b3d3a] hover:bg-[#eef5f0]"><ArrowRight className="h-4 w-4" />العودة</Link></div></header>
    <main className="mx-auto max-w-5xl px-5 py-10 sm:px-8 sm:py-16"><div className="rounded-[2rem] bg-[#0b3d3a] p-7 text-white shadow-xl sm:p-10"><p className="text-sm font-semibold tracking-[0.14em] text-[#b7d8c5]">{eyebrow}</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-5xl">{title}</h1><p className="mt-5 max-w-3xl text-sm leading-8 text-white/75 sm:text-base">{intro}</p><p className="mt-5 text-xs text-white/55">آخر تحديث: {updatedAt}</p></div><div className="mt-6 rounded-[2rem] border border-[#dce7df] bg-white p-6 shadow-sm sm:p-10"><div className="mb-8 rounded-2xl border border-[#dce7df] bg-[#fbfdfb] p-5"><p className="text-sm font-bold text-[#17332f]">بيانات الجهة القانونية والتواصل</p><div className="mt-4 grid gap-3 text-sm leading-7 text-[#586e63] sm:grid-cols-2"><p><strong className="text-[#17332f]">الجهة:</strong> {LEGAL_ENTITY.nameAr} ({LEGAL_ENTITY.nameEn})</p><p><strong className="text-[#17332f]">السجل التجاري:</strong> <span dir="ltr">{LEGAL_ENTITY.commercialRegistration}</span></p><p><strong className="text-[#17332f]">الرقم الضريبي:</strong> <span dir="ltr">{LEGAL_ENTITY.vatNumber}</span></p><p><strong className="text-[#17332f]">الهاتف:</strong> <span dir="ltr">{LEGAL_ENTITY.phone}</span></p><p className="sm:col-span-2"><strong className="text-[#17332f]">العنوان:</strong> {LEGAL_ENTITY.address}</p><p><strong className="text-[#17332f]">البريد الرسمي:</strong> <a className="text-[#0b3d3a] underline" dir="ltr" href={`mailto:${LEGAL_ENTITY.email}`}>{LEGAL_ENTITY.email}</a></p><p><strong className="text-[#17332f]">طلبات الخصوصية:</strong> <a className="text-[#0b3d3a] underline" dir="ltr" href={`mailto:${LEGAL_ENTITY.privacyEmail}`}>{LEGAL_ENTITY.privacyEmail}</a></p></div></div><div className="mb-8 rounded-2xl border border-[#dce7df] bg-[#f7fbf8] p-4 text-sm leading-7 text-[#385b4d]"><p className="font-semibold text-[#17332f]">سجل إصدارات السياسة</p><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs">{LEGAL_POLICY_HISTORY.map((item) => <span key={item.version}>{item.labelAr}: <span dir="ltr">{item.version}</span> · نافذ من <span dir="ltr">{item.effectiveAt}</span></span>)}</div></div><div className="mb-8 flex items-start gap-3 rounded-2xl bg-[#f0f6f2] p-4 text-sm leading-7 text-[#385b4d]"><ShieldCheck className="mt-1 h-5 w-5 shrink-0 text-[#0b3d3a]" /><p>هذه الصفحة مسودة تشغيلية مخصصة لمنصة {PRODUCT_BRAND.bilingual}. ينبغي مراجعتها واعتمادها من مستشار قانوني مختص قبل نشرها كوثيقة نهائية ملزمة.</p></div><div className="space-y-9">{sections.map((section, index) => <section key={section.title} className="border-b border-[#edf1ee] pb-8 last:border-0 last:pb-0"><div className="flex items-baseline gap-3"><span className="text-sm font-bold text-[#4c8067]">{String(index + 1).padStart(2, "0")}</span><h2 className="text-xl font-bold text-[#17332f]">{section.title}</h2></div><div className="mt-4 text-sm leading-8 text-[#586e63]">{section.body}</div></section>)}</div></div></main><MarketingFooter /></div>;
}
