import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, BarChart3, CheckCircle2, ClipboardList, FileWarning, Loader2, Plus, Send, ShieldAlert, Target, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const priorities = { low: "منخفضة", normal: "عادية", high: "عالية", critical: "حرجة" } as const;
const taskStatuses = { new: "جديدة", assigned: "مسندة", in_progress: "قيد التنفيذ", waiting: "بانتظار رد", blocked: "متوقفة", escalated: "مصعّدة", completed: "مكتملة", cancelled: "ملغاة" } as const;
const issueStatuses = { new: "جديدة", assigned: "مسندة", investigation: "تحقيق", action_required: "إجراء مطلوب", resolved: "محلولة", closed: "مغلقة" } as const;

export function OperationsManagerWorkspace({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const enabled = Boolean(tenantId && companyId);
  const input = useMemo(() => ({ tenantId: tenantId ?? 0, companyId: companyId ?? 0 }), [tenantId, companyId]);
  const dashboard = trpc.operationsControl.dashboard.useQuery(input, { enabled, retry: false });
  const summary = trpc.operationsControl.generateSummary.useQuery(input, { enabled, retry: false });
  const utils = trpc.useUtils();
  const [taskTitle, setTaskTitle] = useState("");
  const [taskDescription, setTaskDescription] = useState("");
  const [taskPriority, setTaskPriority] = useState("normal");
  const [issueTitle, setIssueTitle] = useState("");
  const [issueDescription, setIssueDescription] = useState("");
  const [issueSeverity, setIssueSeverity] = useState("medium");
  const [requestDescription, setRequestDescription] = useState("");
  const refresh = () => void utils.operationsControl.dashboard.invalidate(input);
  const createTask = trpc.operationsControl.createTask.useMutation({ onSuccess: () => { toast.success("تم إنشاء المهمة التشغيلية."); setTaskTitle(""); setTaskDescription(""); refresh(); }, onError: (e) => toast.error(e.message) });
  const createIssue = trpc.operationsControl.createIssue.useMutation({ onSuccess: () => { toast.success("تم تسجيل المشكلة التشغيلية."); setIssueTitle(""); setIssueDescription(""); refresh(); }, onError: (e) => toast.error(e.message) });
  const createRequest = trpc.operationsControl.createRequest.useMutation({ onSuccess: () => { toast.success("تم تسجيل الطلب الداخلي."); setRequestDescription(""); refresh(); }, onError: (e) => toast.error(e.message) });
  const updateTask = trpc.operationsControl.updateTask.useMutation({ onSuccess: refresh, onError: (e) => toast.error(e.message) });
  if (!enabled) return null;
  if (dashboard.isLoading) return <Card dir="rtl" className="border-0 shadow-sm"><CardContent className="flex items-center gap-2 p-8 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />تحميل مركز العمليات...</CardContent></Card>;
  if (dashboard.error) return <Card dir="rtl" className="border border-[#f1d8d2] shadow-sm"><CardContent className="p-6 text-sm text-[#77362d]">مركز العمليات مقيد: {dashboard.error.message}</CardContent></Card>;
  const data = dashboard.data;
  if (!data) return null;
  return <section id="ops-control-center" dir="rtl" className="space-y-5">
    <Card id="ops-interventions" className="border-0 bg-[#103d3a] text-white shadow-sm"><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#b7d8c5]">Operations Control Center</p><h2 className="mt-2 text-2xl font-bold">غرفة التحكم التشغيلية</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-white/75">راقب التنفيذ، عالج التعثرات، صعّد المخاطر، وقِس الأداء دون الوصول إلى القيود أو الحسابات البنكية أو إعدادات الضرائب.</p></div><Badge className="w-fit bg-white/15 px-3 py-1.5 text-white hover:bg-white/20">مدير العمليات</Badge></CardContent></Card>
    <Card className="border-0 bg-[#f7fbf8] shadow-sm"><CardContent className="flex flex-col gap-3 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-semibold text-[#5c7b6c]">التقرير التنفيذي المختصر</p><p className="mt-1 text-lg font-bold text-[#18332f]">{summary.data?.overallStatus ?? "جارٍ احتساب الحالة"}</p><p className="mt-1 text-xs text-muted-foreground">المهام المنجزة {summary.data?.completedTasks ?? 0} · المتأخر {summary.data?.overdueTasks ?? 0} · المشكلات الحرجة {summary.data?.criticalIssues ?? 0}</p></div><div className="flex flex-wrap gap-2">{(summary.data?.recommendedActions ?? []).slice(0, 2).map((action) => <Badge key={action} variant="outline">{action}</Badge>)}</div></CardContent></Card>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={ClipboardList} label="مهام مفتوحة" value={data.metrics.openTasks} /><Metric icon={AlertTriangle} label="مهام متأخرة" value={data.metrics.overdueTasks} tone="text-[#a14537]" /><Metric icon={ShieldAlert} label="مشكلات حرجة" value={data.metrics.criticalIssues} tone="text-[#9c4438]" /><Metric icon={Target} label="نسبة الإنجاز" value={`${data.metrics.completionRate}%`} tone="text-[#31557e]" /></div>
    <div className="grid gap-4 xl:grid-cols-[1.15fr_0.85fr]"><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShieldAlert className="h-5 w-5 text-[#a14537]" />يحتاج تدخلي اليوم</CardTitle><p className="text-sm text-muted-foreground">الأعمال الحرجة والمتوقفة والمشكلات التي تحتاج قراراً تشغيلياً.</p></CardHeader><CardContent className="space-y-2">{data.intervention.map((item) => <div key={`${item.type}-${item.id}`} className="flex items-center justify-between rounded-xl border border-[#eadbd6] bg-[#fffafa] p-3"><div><p className="font-semibold text-[#3a2926]">{item.title}</p><p className="mt-1 text-xs text-[#8b716a]">{item.type === "critical_issue" ? "مشكلة حرجة" : item.type === "blocked_task" ? "مهمة متوقفة" : "مهمة حرجة"}</p></div><Badge variant="outline">تدخل</Badge></div>)}{!data.intervention.length && <p className="rounded-xl bg-[#f7f9f7] p-4 text-sm text-muted-foreground">لا توجد عناصر حرجة تحتاج تدخلاً حالياً.</p>}</CardContent></Card><Card id="ops-kpis" className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BarChart3 className="h-5 w-5 text-[#0b3d3a]" />مؤشرات التشغيل الأساسية</CardTitle></CardHeader><CardContent className="grid grid-cols-2 gap-2 text-center">{[["المهام الحرجة", data.metrics.criticalTasks], ["المشكلات المفتوحة", data.metrics.openIssues], ["الطلبات المعلقة", data.metrics.openRequests], ["المتوقف", data.metrics.blockedTasks]].map(([label, value]) => <div key={String(label)} className="rounded-lg bg-[#f7f9f7] p-3"><strong className="block text-xl text-[#0b3d3a]" dir="ltr">{String(value)}</strong><span className="text-xs text-muted-foreground">{String(label)}</span></div>)}</CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-3"><Card id="ops-task-form" className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">مهمة تشغيلية</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={taskTitle} onChange={(e) => setTaskTitle(e.target.value)} placeholder="عنوان المهمة" /><Textarea value={taskDescription} onChange={(e) => setTaskDescription(e.target.value)} placeholder="التعليمات ووصف التنفيذ" /><select className="h-10 w-full rounded-md border border-input bg-background px-2 text-sm" value={taskPriority} onChange={(e) => setTaskPriority(e.target.value)} aria-label="أولوية المهمة">{Object.entries(priorities).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><Button disabled={!taskTitle.trim() || createTask.isPending} onClick={() => createTask.mutate({ ...input, title: taskTitle.trim(), description: taskDescription.trim() || undefined, priority: taskPriority as keyof typeof priorities })}><Plus className="ml-2 h-4 w-4" />إنشاء مهمة</Button></CardContent></Card><Card id="ops-issue-form" className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FileWarning className="h-5 w-5 text-[#a14537]" />مشكلة أو حادث</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={issueTitle} onChange={(e) => setIssueTitle(e.target.value)} placeholder="عنوان المشكلة" /><Textarea value={issueDescription} onChange={(e) => setIssueDescription(e.target.value)} placeholder="ماذا حدث؟ وما أثره؟" /><select className="h-10 w-full rounded-md border border-input bg-background px-2 text-sm" value={issueSeverity} onChange={(e) => setIssueSeverity(e.target.value)} aria-label="خطورة المشكلة"><option value="low">منخفضة</option><option value="medium">متوسطة</option><option value="high">عالية</option><option value="critical">حرجة</option></select><Button variant="outline" disabled={!issueTitle.trim() || !issueDescription.trim() || createIssue.isPending} onClick={() => createIssue.mutate({ ...input, title: issueTitle.trim(), description: issueDescription.trim(), severity: issueSeverity as "low" | "medium" | "high" | "critical" })}><AlertTriangle className="ml-2 h-4 w-4" />تسجيل مشكلة</Button></CardContent></Card><Card id="ops-request-form" className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">طلب داخلي</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="نوع الطلب: صيانة، تجهيز، دعم..." /><Textarea value={requestDescription} onChange={(e) => setRequestDescription(e.target.value)} placeholder="وصف الطلب والقسم أو الفرع المعني" /><Button variant="outline" disabled={!requestDescription.trim() || createRequest.isPending} onClick={() => createRequest.mutate({ ...input, requestType: "internal", description: requestDescription.trim() })}><Send className="ml-2 h-4 w-4" />إرسال الطلب</Button></CardContent></Card></div>
    <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CheckCircle2 className="h-5 w-5 text-[#0b3d3a]" />مركز العمليات</CardTitle><p className="text-sm text-muted-foreground">عرض الأعمال حسب الحالة والأولوية والمسؤول، مع تحديث مباشر للمهمة.</p></CardHeader><CardContent className="space-y-2">{data.tasks.slice(0, 12).map(({ task, assignee }) => <div key={task.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-[#e2e8e3] p-3"><div><p className="font-semibold">{task.title}</p><p className="text-xs text-muted-foreground">{priorities[task.priority]} · {assignee?.name || assignee?.email || "غير مسندة"} · {task.department || "تشغيل عام"}</p></div><select value={task.status} onChange={(e) => updateTask.mutate({ ...input, taskId: task.id, status: e.target.value as keyof typeof taskStatuses })} className="h-9 rounded-md border border-input bg-background px-2 text-xs" aria-label="حالة المهمة">{Object.entries(taskStatuses).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>)}{!data.tasks.length && <p className="text-sm text-muted-foreground">لا توجد مهام تشغيلية بعد.</p>}</CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2"><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">المشكلات التشغيلية</CardTitle></CardHeader><CardContent className="space-y-2">{data.issues.slice(0, 8).map(({ issue, assignee }) => <div key={issue.id} className="rounded-xl border border-[#e2e8e3] p-3"><div className="flex items-center justify-between gap-2"><p className="font-semibold">{issue.title}</p><Badge variant={issue.severity === "critical" ? "destructive" : "outline"}>{issue.severity === "critical" ? "حرجة" : issueStatuses[issue.status]}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{assignee?.name || "غير مسندة"} · {issue.department || "تشغيل عام"}</p></div>)}{!data.issues.length && <p className="text-sm text-muted-foreground">لا توجد مشكلات مسجلة بعد.</p>}</CardContent></Card><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><UsersRound className="h-5 w-5 text-[#0b3d3a]" />الأداء التشغيلي</CardTitle></CardHeader><CardContent className="space-y-3">{data.branches.length ? data.branches.map((branch) => <div key={branch.id} className="flex items-center justify-between rounded-lg bg-[#f7f9f7] p-3"><span className="font-medium">{branch.nameAr}</span><Badge variant="outline">{branch.isActive ? "نشط" : "متوقف"}</Badge></div>) : <p className="text-sm text-muted-foreground">لا توجد فروع مفعّلة؛ تُدار الشركة حالياً كوحدة واحدة.</p>}<p className="border-t pt-3 text-xs text-muted-foreground">لا تتضمن هذه المساحة القيود أو دفتر الأستاذ أو الحسابات البنكية أو إعدادات الضرائب.</p></CardContent></Card></div>
  </section>;
}

function Metric({ icon: Icon, label, value, tone = "text-[#0b3d3a]" }: { icon: typeof ClipboardList; label: string; value: number | string; tone?: string }) { return <Card className="border-0 shadow-sm"><CardContent className="p-4"><Icon className={`h-5 w-5 ${tone}`} /><strong className="mt-3 block text-2xl text-[#18332f]" dir="ltr">{value}</strong><p className="mt-1 text-xs text-muted-foreground">{label}</p></CardContent></Card>; }
