import { useMemo, useState } from "react";
import type { LucideIcon } from "lucide-react";
import { BarChart3, BellRing, CheckCircle2, ClipboardCheck, FileText, ListFilter, Megaphone, Target, UsersRound } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

const stageLabels: Record<string, string> = { new_lead: "عميل محتمل جديد", qualified: "مؤهل", discovery: "اكتشاف", proposal: "عرض سعر", negotiation: "تفاوض", won: "مغلقة - فوز", lost: "مغلقة - خسارة", on_hold: "متوقفة" };
const money = (value: number | string | undefined) => new Intl.NumberFormat("en-US", { style: "currency", currency: "SAR", maximumFractionDigits: 0 }).format(Number(value ?? 0));
const isoToday = () => new Date().toISOString().slice(0, 10);

export function SalesSupervisorWorkspace({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const enabled = Boolean(tenantId && companyId);
  const base = useMemo(() => ({ tenantId: tenantId ?? 0, companyId: companyId ?? 0 }), [tenantId, companyId]);
  const assignees = trpc.sales.listSalesAssignees.useQuery(base, { enabled });
  const customers = trpc.sales.listCustomers.useQuery(base, { enabled });
  const opportunities = trpc.sales.listSalesOpportunities.useQuery({ ...base, stage: "all" }, { enabled });
  const activities = trpc.sales.listSalesActivities.useQuery({ ...base, status: "all" }, { enabled });
  const quotations = trpc.sales.listQuotations.useQuery(base, { enabled });
  const approvalRequests = trpc.approvals.listPending.useQuery({ ...base, documentType: "quotation_discount" }, { enabled });
  const [selectedRep, setSelectedRep] = useState("all");
  const [showLeadForm, setShowLeadForm] = useState(false);
  const [showTaskForm, setShowTaskForm] = useState(false);
  const [leadTitle, setLeadTitle] = useState("");
  const [leadCustomerId, setLeadCustomerId] = useState("");
  const [leadValue, setLeadValue] = useState("0");
  const [leadSource, setLeadSource] = useState("");
  const [taskSubject, setTaskSubject] = useState("");
  const [taskCustomerId, setTaskCustomerId] = useState("");
  const [taskRepId, setTaskRepId] = useState("");
  const [taskDate, setTaskDate] = useState(isoToday());
  const repRows = assignees.data ?? [];
  const opportunityRows = (opportunities.data ?? []).filter((row) => selectedRep === "all" || String(row.opportunity.ownerUserId) === selectedRep);
  const activityRows = (activities.data ?? []).filter((row) => selectedRep === "all" || String(row.activity.ownerUserId) === selectedRep);
  const customerRows = customers.data ?? [];
  const quotationRows = quotations.data ?? [];
  const today = isoToday();
  const metrics = {
    openPipeline: opportunityRows.filter((row) => !["won", "lost"].includes(row.opportunity.stage)).reduce((sum, row) => sum + Number(row.opportunity.expectedValue ?? 0), 0),
    weightedPipeline: opportunityRows.filter((row) => !["won", "lost"].includes(row.opportunity.stage)).reduce((sum, row) => sum + Number(row.opportunity.expectedValue ?? 0) * Number(row.opportunity.probability ?? 0) / 100, 0),
    won: opportunityRows.filter((row) => row.opportunity.stage === "won").length,
    lost: opportunityRows.filter((row) => row.opportunity.stage === "lost").length,
    newLeads: opportunityRows.filter((row) => row.opportunity.stage === "new_lead").length,
    sentQuotes: quotationRows.filter((quote) => ["sent", "accepted", "rejected"].includes(quote.status)).length,
    overdue: activityRows.filter((row) => row.activity.status === "open" && row.activity.dueDate && String(row.activity.dueDate).slice(0, 10) < today).length,
    meetings: activityRows.filter((row) => row.activity.activityType === "meeting").length,
  };
  const conversionRate = opportunityRows.length ? (metrics.won / opportunityRows.length) * 100 : 0;
  const lostReasons = Object.entries(opportunityRows.filter((row) => row.opportunity.stage === "lost").reduce<Record<string, number>>((acc, row) => { const key = row.opportunity.lostReason || "other"; acc[key] = (acc[key] || 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 5);
  const leadSources = Object.entries(opportunityRows.reduce<Record<string, number>>((acc, row) => { const key = row.opportunity.source || "غير محدد"; acc[key] = (acc[key] || 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 5);
  const serviceInterest = Object.entries(opportunityRows.reduce<Record<string, number>>((acc, row) => { const key = row.opportunity.serviceInterest || "غير محدد"; acc[key] = (acc[key] || 0) + 1; return acc; }, {})).sort((a, b) => b[1] - a[1]).slice(0, 5);
  const createLead = trpc.sales.createSalesOpportunity.useMutation({ onSuccess: async () => { toast.success("تم إنشاء العميل المحتمل وتوزيعه."); setLeadTitle(""); setLeadCustomerId(""); setLeadValue("0"); setLeadSource(""); await opportunities.refetch(); }, onError: (error) => toast.error(error.message) });
  const createTask = trpc.sales.createSalesActivity.useMutation({ onSuccess: async () => { toast.success("تم إنشاء المهمة للممثل."); setTaskSubject(""); await activities.refetch(); }, onError: (error) => toast.error(error.message) });
  const reassignCustomer = trpc.sales.updateCustomer.useMutation({ onSuccess: async () => { toast.success("تم تحديث مسؤول العميل."); await customers.refetch(); }, onError: (error) => toast.error(error.message) });
  const reassignOpportunity = trpc.sales.reassignSalesOpportunity.useMutation({ onSuccess: async () => { toast.success("تم إعادة توزيع الفرصة."); await opportunities.refetch(); }, onError: (error) => toast.error(error.message) });
  if (!enabled) return null;
  const submitLead = () => { const owner = selectedRep !== "all" ? Number(selectedRep) : Number(repRows[0]?.userId); if (!owner || !leadCustomerId || !leadTitle.trim()) return toast.error("اختر العميل والممثل واكتب اسم العميل المحتمل."); createLead.mutate({ ...base, customerId: Number(leadCustomerId), ownerUserId: owner, title: leadTitle.trim(), expectedValue: leadValue || "0", source: leadSource.trim() || undefined, stage: "new_lead", probability: 10 }); };
  const submitTask = () => { if (!taskRepId || !taskCustomerId || !taskSubject.trim()) return toast.error("أكمل الممثل والعميل وموضوع المهمة."); createTask.mutate({ ...base, customerId: Number(taskCustomerId), ownerUserId: Number(taskRepId), subject: taskSubject.trim(), activityType: "task", dueDate: taskDate || undefined }); };
  return <section className="space-y-5" dir="rtl">
    <Card className="border-0 bg-[#103d3a] text-white shadow-sm"><CardContent className="p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold tracking-[0.16em] text-[#b8d9c5]">SALES SUPERVISOR DESK</p><h2 className="mt-2 text-2xl font-bold">لوحة إشراف المبيعات</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-white/75">رؤية موحدة على مستوى الشركة لمتابعة الممثلين والفرص والعروض والتدخلات اليومية، دون فتح الوحدات المحاسبية أو الإدارية.</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => setShowLeadForm((value) => !value)} className="bg-white text-[#0b3d3a] hover:bg-[#eef5f0]"><UsersRound className="ml-2 h-4 w-4" />توزيع Lead</Button><Button onClick={() => setShowTaskForm((value) => !value)} variant="outline" className="border-white/30 bg-white/10 text-white hover:bg-white/20"><ClipboardCheck className="ml-2 h-4 w-4" />مهمة لممثل</Button></div></div></CardContent></Card>
    <div className="flex flex-col gap-3 rounded-2xl border border-[#e1e9e3] bg-white p-4 sm:flex-row sm:items-end"><div className="min-w-0 flex-1"><Label>تصفية حسب ممثل المبيعات</Label><Select value={selectedRep} onValueChange={setSelectedRep}><SelectTrigger className="mt-2"><SelectValue placeholder="كل الممثلين" /></SelectTrigger><SelectContent><SelectItem value="all">كل الممثلين</SelectItem>{repRows.map((rep) => <SelectItem key={rep.userId} value={String(rep.userId)}>{rep.name || rep.email}</SelectItem>)}</SelectContent></Select></div><p className="text-sm text-muted-foreground">{repRows.length} ممثلين نشطين · {customerRows.length} عميلًا · {opportunityRows.length} فرصة في النطاق</p></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Target} label="قيمة Pipeline" value={money(metrics.openPipeline)} /><Metric icon={Target} label="Weighted Pipeline" value={money(metrics.weightedPipeline)} /><Metric icon={UsersRound} label="Leads جديدة" value={metrics.newLeads} /><Metric icon={FileText} label="عروض مرسلة" value={metrics.sentQuotes} /><Metric icon={CheckCircle2} label="صفقات فائزة" value={metrics.won} /><Metric icon={BarChart3} label="Conversion Rate" value={`${conversionRate.toFixed(1)}%`} /><Metric icon={ClipboardCheck} label="متابعات متأخرة" value={metrics.overdue} /><Metric icon={BellRing} label="طلبات خصم معلقة" value={approvalRequests.data?.length ?? 0} /></div>
    {(showLeadForm || showTaskForm) && <div className="grid gap-5 lg:grid-cols-2">{showLeadForm && <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">Lead Distribution Center</CardTitle></CardHeader><CardContent className="space-y-3"><div><Label>العميل</Label><Select value={leadCustomerId} onValueChange={setLeadCustomerId}><SelectTrigger><SelectValue placeholder="اختر العميل" /></SelectTrigger><SelectContent>{customerRows.map((customer) => <SelectItem key={customer.id} value={String(customer.id)}>{customer.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="supervisor-lead-title">اسم الفرصة</Label><Input id="supervisor-lead-title" value={leadTitle} onChange={(event) => setLeadTitle(event.target.value)} placeholder="مثال: طلب نظام مالي" /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>قيمة متوقعة</Label><Input dir="ltr" inputMode="decimal" value={leadValue} onChange={(event) => setLeadValue(event.target.value)} /></div><div><Label>مصدر العميل</Label><Input value={leadSource} onChange={(event) => setLeadSource(event.target.value)} placeholder="Referral / Website" /></div></div><Button className="w-full bg-[#0b3d3a]" disabled={createLead.isPending} onClick={submitLead}>توزيع وإنشاء Lead</Button></CardContent></Card>}{showTaskForm && <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">مهمة إشرافية لممثل المبيعات</CardTitle></CardHeader><CardContent className="space-y-3"><div><Label>الممثل</Label><Select value={taskRepId} onValueChange={setTaskRepId}><SelectTrigger><SelectValue placeholder="اختر الممثل" /></SelectTrigger><SelectContent>{repRows.map((rep) => <SelectItem key={rep.userId} value={String(rep.userId)}>{rep.name || rep.email}</SelectItem>)}</SelectContent></Select></div><div><Label>العميل</Label><Select value={taskCustomerId} onValueChange={setTaskCustomerId}><SelectTrigger><SelectValue placeholder="اختر العميل" /></SelectTrigger><SelectContent>{customerRows.map((customer) => <SelectItem key={customer.id} value={String(customer.id)}>{customer.name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="supervisor-task-subject">التعليمات</Label><Textarea id="supervisor-task-subject" value={taskSubject} onChange={(event) => setTaskSubject(event.target.value)} placeholder="أكمل التواصل وأضف النتيجة إلى سجل النشاط" /></div><div><Label>الموعد</Label><Input type="date" dir="ltr" value={taskDate} onChange={(event) => setTaskDate(event.target.value)} /></div><Button className="w-full bg-[#0b3d3a]" disabled={createTask.isPending} onClick={submitTask}>إسناد المهمة</Button></CardContent></Card>}</div>}
    <div className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]"><Card className="border-0 shadow-sm"><CardHeader className="flex flex-row items-center justify-between gap-3"><div><CardTitle className="text-base">أداء ممثلي المبيعات</CardTitle><p className="mt-1 text-sm text-muted-foreground">الترتيب يعتمد على النتائج وقيمة الـPipeline، وليس عدد الاتصالات وحده.</p></div><Badge variant="outline">{repRows.length} ممثل</Badge></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b text-right text-muted-foreground"><th className="p-3">الممثل</th><th className="p-3">الفرص</th><th className="p-3">Pipeline</th><th className="p-3">فوز</th><th className="p-3">متأخر</th><th className="p-3">الحالة</th></tr></thead><tbody>{repRows.map((rep) => { const rows = (opportunities.data ?? []).filter((row) => row.opportunity.ownerUserId === rep.userId); const repActivities = (activities.data ?? []).filter((row) => row.activity.ownerUserId === rep.userId); const won = rows.filter((row) => row.opportunity.stage === "won").length; const pipeline = rows.filter((row) => !["won", "lost"].includes(row.opportunity.stage)).reduce((sum, row) => sum + Number(row.opportunity.expectedValue ?? 0), 0); const overdue = repActivities.filter((row) => row.activity.status === "open" && row.activity.dueDate && String(row.activity.dueDate).slice(0, 10) < today).length; return <tr key={rep.userId} className="border-b last:border-0"><td className="p-3 font-medium">{rep.name || rep.email}</td><td className="p-3">{rows.length}</td><td className="p-3" dir="ltr">{money(pipeline)}</td><td className="p-3">{won}</td><td className="p-3">{overdue}</td><td className="p-3"><Badge variant={overdue > 0 ? "destructive" : "outline"}>{overdue > 0 ? "يحتاج تدخل" : "مستقر"}</Badge></td></tr>; })}</tbody></table></div>{!repRows.length && <Empty text="لا يوجد ممثلون نشطون في الشركة." />}</CardContent></Card><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">ماذا يحتاج تدخلي اليوم؟</CardTitle></CardHeader><CardContent className="space-y-3"><Alert icon={Megaphone} text={`${metrics.overdue} متابعات متأخرة تحتاج مراجعة.`} /><Alert icon={FileText} text={`${approvalRequests.data?.length ?? 0} طلبات خصم تنتظر الاعتماد.`} /><Alert icon={Target} text={`${opportunityRows.filter((row) => Number(row.opportunity.probability) >= 70 && !["won", "lost"].includes(row.opportunity.stage)).length} فرص عالية الاحتمالية مفتوحة.`} /><Alert icon={BellRing} text={`${quotationRows.filter((quote) => quote.status === "sent").length} عروض مرسلة تنتظر رد العميل.`} /></CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ListFilter className="h-5 w-5 text-[#0b3d3a]" />Company Sales Pipeline</CardTitle></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-2">{Object.entries(stageLabels).map(([stage, label]) => { const count = opportunityRows.filter((row) => row.opportunity.stage === stage).length; const value = opportunityRows.filter((row) => row.opportunity.stage === stage).reduce((sum, row) => sum + Number(row.opportunity.expectedValue ?? 0), 0); return <div key={stage} className="rounded-xl bg-[#f7faf7] p-3"><div className="flex items-center justify-between gap-2"><span className="text-sm font-medium">{label}</span><Badge variant="outline">{count}</Badge></div><p className="mt-2 text-sm text-[#0b5a45]" dir="ltr">{money(value)}</p></div>; })}</div></CardContent></Card><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">أحدث الفرص والمتابعات</CardTitle></CardHeader><CardContent className="space-y-2">{opportunityRows.slice(0, 6).map((row) => <div key={row.opportunity.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-medium">{row.opportunity.title}</p><p className="text-xs text-muted-foreground">{row.customerName ?? "—"} · {stageLabels[row.opportunity.stage] ?? row.opportunity.stage}</p></div><span className="text-sm font-semibold text-[#0b5a45]" dir="ltr">{money(row.opportunity.expectedValue)}</span></div>)}{!opportunityRows.length && <Empty text="لا توجد فرص في النطاق الحالي." />}</CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-3"><InsightCard title="تحليل الصفقات المفقودة" items={lostReasons.map(([label, count]) => [`${label === "other" ? "سبب آخر" : label}`, `${count} صفقة`])} empty="لا توجد صفقات مفقودة." /><InsightCard title="مصادر العملاء المحتملين" items={leadSources.map(([label, count]) => [label, `${count} فرصة`])} empty="لم تُسجل مصادر بعد." /><InsightCard title="الخدمات والمنتجات محل الاهتمام" items={serviceInterest.map(([label, count]) => [label, `${count} فرصة`])} empty="لم تُسجل اهتمامات خدمية بعد." /></div>
    <Card className="border-0 shadow-sm"><CardHeader className="flex flex-row items-center justify-between gap-3"><div><CardTitle className="text-base">مراجعة عروض الأسعار</CardTitle><p className="mt-1 text-sm text-muted-foreground">عرض تجاري فقط؛ تحويل العرض إلى فاتورة يتم في قسم الفوترة بصلاحية مالية مستقلة.</p></div><Badge variant="outline">{quotationRows.length} عرض</Badge></CardHeader><CardContent className="space-y-2">{quotationRows.slice(0, 8).map((quote) => <div key={quote.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><p className="font-medium">{quote.quoteNumber}</p><p className="text-xs text-muted-foreground">{quote.status} · {quote.issueDate ? String(quote.issueDate).slice(0, 10) : "—"}</p></div><span className="font-semibold text-[#0b5a45]" dir="ltr">{money(quote.grandTotal)}</span></div>)}{!quotationRows.length && <Empty text="لا توجد عروض أسعار في النطاق الحالي." />}</CardContent></Card>
    <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">إعادة إسناد سريعة</CardTitle><p className="text-sm text-muted-foreground">يمكن للمشرف نقل مسؤولية العميل أو الفرصة داخل نطاق المبيعات فقط.</p></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><div className="space-y-3"><Label>العميل</Label>{customerRows.slice(0, 8).map((customer) => <div key={customer.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3"><span className="text-sm">{customer.name}</span><Select value={customer.salesOwnerUserId ? String(customer.salesOwnerUserId) : "unassigned"} onValueChange={(value) => reassignCustomer.mutate({ ...base, customerId: customer.id, name: customer.name, salesOwnerUserId: value === "unassigned" ? null : Number(value), accountTier: customer.accountTier, vatNumber: customer.vatNumber ?? undefined, email: customer.email ?? undefined, phone: customer.phone ?? undefined })}><SelectTrigger className="w-44"><SelectValue placeholder="اختر المسؤول" /></SelectTrigger><SelectContent><SelectItem value="unassigned">غير معين</SelectItem>{repRows.map((rep) => <SelectItem key={rep.userId} value={String(rep.userId)}>{rep.name || rep.email}</SelectItem>)}</SelectContent></Select></div>)}</div><div className="space-y-3"><Label>الفرصة</Label>{opportunityRows.slice(0, 8).map((row) => <div key={row.opportunity.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl border p-3"><span className="min-w-0 truncate text-sm">{row.opportunity.title}</span><Select value={String(row.opportunity.ownerUserId)} onValueChange={(value) => reassignOpportunity.mutate({ ...base, opportunityId: row.opportunity.id, ownerUserId: Number(value) })}><SelectTrigger className="w-44"><SelectValue placeholder="اختر المسؤول" /></SelectTrigger><SelectContent>{repRows.map((rep) => <SelectItem key={rep.userId} value={String(rep.userId)}>{rep.name || rep.email}</SelectItem>)}</SelectContent></Select></div>)}</div></CardContent></Card>
  </section>;
}

function Metric({ icon: Icon, label, value }: { icon: LucideIcon; label: string; value: string | number }) { return <Card className="border-0 shadow-sm"><CardContent className="p-4"><div className="flex items-center justify-between"><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#e6f0eb] text-[#0b5a45]"><Icon className="h-4 w-4" /></div><strong className="text-lg text-[#18332f]" dir="ltr">{value}</strong></div><p className="mt-3 text-sm text-muted-foreground">{label}</p></CardContent></Card>; }
function Alert({ icon: Icon, text }: { icon: LucideIcon; text: string }) { return <div className="flex items-center gap-3 rounded-xl bg-[#f7faf7] p-3 text-sm"><Icon className="h-4 w-4 shrink-0 text-[#0b5a45]" /><span>{text}</span></div>; }
function InsightCard({ title, items, empty }: { title: string; items: string[][]; empty: string }) { return <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent className="space-y-2">{items.length ? items.map(([label, value]) => <div key={`${label}-${value}`} className="flex items-center justify-between gap-3 rounded-xl bg-[#f7faf7] p-3 text-sm"><span className="truncate">{label}</span><Badge variant="outline">{value}</Badge></div>) : <Empty text={empty} />}</CardContent></Card>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed p-5 text-center text-sm text-muted-foreground">{text}</p>; }
