import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { FileCog, Landmark, Loader2, ReceiptText } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const isoDate = (value: Date | string) => new Date(value).toISOString().slice(0, 10);

export function TaxInvoicingSettings({ tenantId, companyId }: { tenantId?: number; companyId?: number }) {
  const enabled = Boolean(tenantId && companyId); const input = { tenantId: tenantId ?? 0, companyId: companyId ?? 0 };
  const data = trpc.finance.setupData.useQuery(input, { enabled }); const utils = trpc.useUtils();
  const [registrationNumber, setRegistrationNumber] = useState(""); const [rate, setRate] = useState("1500"); const [frequency, setFrequency] = useState<"monthly" | "quarterly" | "annual">("quarterly");
  const [periodName, setPeriodName] = useState(""); const [periodStart, setPeriodStart] = useState(new Date().toISOString().slice(0, 10)); const [periodEnd, setPeriodEnd] = useState(new Date().toISOString().slice(0, 10));
  const [terms, setTerms] = useState("30"); const [invoiceType, setInvoiceType] = useState<"standard" | "simplified">("standard"); const [footerNote, setFooterNote] = useState("");
  const profile = data.data?.taxProfiles.find((item) => item.taxType === "vat"); const preferences = data.data?.invoicingPreferences;
  useEffect(() => { if (!profile) return; setRegistrationNumber(profile.registrationNumber ?? ""); setRate(String(profile.defaultRateBps)); setFrequency(profile.filingFrequency); }, [profile?.id]);
  useEffect(() => { if (!preferences) return; setTerms(String(preferences.defaultPaymentTermsDays)); setInvoiceType(preferences.defaultInvoiceType); setFooterNote(preferences.footerNoteAr ?? ""); }, [preferences?.id]);
  const refresh = async () => { await utils.finance.setupData.invalidate(input); };
  const saveProfile = trpc.finance.saveTaxProfile.useMutation({ onSuccess: async () => { toast.success("تم حفظ ملف VAT."); await refresh(); }, onError: (error) => toast.error(error.message) });
  const addPeriod = trpc.finance.addTaxPeriod.useMutation({ onSuccess: async () => { setPeriodName(""); toast.success("تمت إضافة فترة VAT."); await refresh(); }, onError: (error) => toast.error(error.message) });
  const updatePeriod = trpc.finance.updateTaxPeriodStatus.useMutation({ onSuccess: async () => { toast.success("تم تحديث حالة فترة VAT."); await refresh(); }, onError: (error) => toast.error(error.message) });
  const savePreferences = trpc.finance.saveInvoicingPreferences.useMutation({ onSuccess: async () => { toast.success("تم حفظ تفضيلات الإصدار."); await refresh(); }, onError: (error) => toast.error(error.message) });
  if (!enabled) return null;
  return <section className="mt-5 grid gap-5 xl:grid-cols-3"><Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#e7f3eb] text-[#0b3d3a]"><Landmark className="h-5 w-5" /></div><div><CardTitle className="text-base">ملف VAT</CardTitle><p className="mt-1 text-sm text-muted-foreground">الرقم والنسبة والدورية الافتراضية للإقرار.</p></div></div></CardHeader><CardContent className="space-y-3"><label className="text-sm font-medium text-[#44564d]">رقم التسجيل<Input className="mt-2" dir="ltr" value={registrationNumber} onChange={(event) => setRegistrationNumber(event.target.value)} /></label><label className="text-sm font-medium text-[#44564d]">النسبة الافتراضية (نقاط أساس)<Input className="mt-2" dir="ltr" inputMode="numeric" value={rate} onChange={(event) => setRate(event.target.value)} /></label><label className="text-sm font-medium text-[#44564d]">دورية الإقرار<select className="mt-2 h-10 w-full rounded-md border border-[#cfd9d2] bg-white px-3 text-sm" value={frequency} onChange={(event) => setFrequency(event.target.value as typeof frequency)}><option value="monthly">شهري</option><option value="quarterly">ربع سنوي</option><option value="annual">سنوي</option></select></label><Button disabled={!registrationNumber.trim() || !rate || saveProfile.isPending} className="w-full bg-[#0b3d3a] hover:bg-[#082f2d]" onClick={() => saveProfile.mutate({ ...input, taxType: "vat", registrationNumber: registrationNumber.trim(), defaultRateBps: Number(rate), filingFrequency: frequency })}>{saveProfile.isPending && <Loader2 className="ml-2 h-4 w-4 animate-spin" />}حفظ ملف VAT</Button></CardContent></Card>

  <Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf1f8] text-[#385b93]"><FileCog className="h-5 w-5" /></div><div><CardTitle className="text-base">فترات VAT</CardTitle><p className="mt-1 text-sm text-muted-foreground">تابع مرحلة تجهيز وإيداع وقفل كل فترة.</p></div></div></CardHeader><CardContent className="space-y-3"><Input value={periodName} onChange={(event) => setPeriodName(event.target.value)} placeholder="اسم الفترة" /><div className="grid grid-cols-2 gap-2"><Input dir="ltr" value={periodStart} onChange={(event) => setPeriodStart(event.target.value)} /><Input dir="ltr" value={periodEnd} onChange={(event) => setPeriodEnd(event.target.value)} /></div><Button variant="outline" disabled={!profile || !periodName.trim() || addPeriod.isPending} onClick={() => profile && addPeriod.mutate({ ...input, taxProfileId: profile.id, name: periodName.trim(), startDate: periodStart, endDate: periodEnd })}>إضافة فترة VAT</Button><div className="space-y-2">{data.data?.taxPeriods.length ? data.data.taxPeriods.map((period) => <div key={period.id} className="rounded-xl border border-[#dce4dd] bg-[#fbfdfb] p-3"><div className="flex items-center justify-between gap-3"><div><p className="font-medium text-[#32453b]">{period.name}</p><p className="mt-1 text-xs text-[#748079]" dir="ltr">{isoDate(period.startDate)} — {isoDate(period.endDate)}</p></div><Badge variant="outline">{period.status}</Badge></div><select value={period.status} disabled={updatePeriod.isPending} onChange={(event) => updatePeriod.mutate({ ...input, taxPeriodId: period.id, status: event.target.value as "open" | "prepared" | "filed" | "locked" })} className="mt-2 h-9 w-full rounded-md border border-[#cfd9d2] bg-white px-2 text-xs"><option value="open">مفتوحة</option><option value="prepared">قيد التجهيز</option><option value="filed">تم الإيداع</option><option value="locked">مقفلة</option></select></div>) : <p className="rounded-xl bg-[#f7f9f7] p-3 text-sm text-[#6d7972]">لا توجد فترات VAT مضافة.</p>}</div></CardContent></Card>

  <Card className="border-0 shadow-sm rounded-2xl"><CardHeader><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#fff3e5] text-[#9a6217]"><ReceiptText className="h-5 w-5" /></div><div><CardTitle className="text-base">تفضيلات الإصدار</CardTitle><p className="mt-1 text-sm text-muted-foreground">إعدادات الفاتورة الافتراضية والعبارة الختامية.</p></div></div></CardHeader><CardContent className="space-y-3"><label className="text-sm font-medium text-[#44564d]">أيام السداد الافتراضية<Input className="mt-2" dir="ltr" inputMode="numeric" value={terms} onChange={(event) => setTerms(event.target.value)} /></label><label className="text-sm font-medium text-[#44564d]">نوع الفاتورة الافتراضي<select className="mt-2 h-10 w-full rounded-md border border-[#cfd9d2] bg-white px-3 text-sm" value={invoiceType} onChange={(event) => setInvoiceType(event.target.value as typeof invoiceType)}><option value="standard">ضريبية</option><option value="simplified">مبسطة</option></select></label><label className="text-sm font-medium text-[#44564d]">عبارة ختامية للمستندات<Textarea className="mt-2" value={footerNote} onChange={(event) => setFooterNote(event.target.value)} /></label><Button disabled={!terms || savePreferences.isPending} className="w-full bg-[#0b3d3a] hover:bg-[#082f2d]" onClick={() => savePreferences.mutate({ ...input, defaultPaymentTermsDays: Number(terms), defaultInvoiceType: invoiceType, footerNoteAr: footerNote.trim() || undefined })}>{savePreferences.isPending && <Loader2 className="ml-2 h-4 w-4 animate-spin" />}حفظ تفضيلات الإصدار</Button></CardContent></Card></section>;
}
